{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.25.aar",
          "url": "oiti-network-0.0.25.aar",
          "size": 43192,
          "sha512": "42b57119143a6773ab23d67bb392e6fa879ff3ee4d7c4e0c8b3c860989168d19e791352f86ec399a14ef094c260f0ae8147bf836d374465257ed538c1419658b",
          "sha256": "f32c0dec2ba99765540b32e973990e85d9a6c209aae090f7f586fabfd3dad816",
          "sha1": "abf95322f77c8bb17abe63d577f91bfec6270da5",
          "md5": "590d5d6559d8217fb6d62a8121ed29e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.25.aar",
          "url": "oiti-network-0.0.25.aar",
          "size": 43192,
          "sha512": "42b57119143a6773ab23d67bb392e6fa879ff3ee4d7c4e0c8b3c860989168d19e791352f86ec399a14ef094c260f0ae8147bf836d374465257ed538c1419658b",
          "sha256": "f32c0dec2ba99765540b32e973990e85d9a6c209aae090f7f586fabfd3dad816",
          "sha1": "abf95322f77c8bb17abe63d577f91bfec6270da5",
          "md5": "590d5d6559d8217fb6d62a8121ed29e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-0.0.25-sources.jar",
          "url": "oiti-network-0.0.25-sources.jar",
          "size": 14159,
          "sha512": "e9a624e83c5e25ded6d7fc9081030f98f72cb0a56e4e203150da0288a3173e63c7288bde511407af3ccc510f6c36c937007553a87c3bb045860c579168cab66c",
          "sha256": "80c1db9c236e9c7b856656d882b0cb9f18ccd198deefcc4eb6eb40d39f55e347",
          "sha1": "8af535529dd059c57609fd228dc1849188752513",
          "md5": "7cddd26b5369481c0217e95d58a41738"
        }
      ]
    }
  ]
}
