{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "remote",
    "version": "2.1.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-2.1.0-beta.aar",
          "url": "remote-2.1.0-beta.aar",
          "size": 61372,
          "sha512": "c273d5c1c94c53a13e2233f06ee350292ea8dc65269c82136a93553edea5a254e15c24913baa07869c9401a9085685e40f0a77ae3a64b204520aa83fc9ce4bb3",
          "sha256": "51018c16d0355f777220cc09f735ec9a0fd1c3cfb698bd405e3d3d37fc04c90e",
          "sha1": "191be71484dfaabfebba24d12686483a4647c52a",
          "md5": "933467f39de3aaed33d80b11bdd87baa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.1.0-beta"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "2.1.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-2.1.0-beta.aar",
          "url": "remote-2.1.0-beta.aar",
          "size": 61372,
          "sha512": "c273d5c1c94c53a13e2233f06ee350292ea8dc65269c82136a93553edea5a254e15c24913baa07869c9401a9085685e40f0a77ae3a64b204520aa83fc9ce4bb3",
          "sha256": "51018c16d0355f777220cc09f735ec9a0fd1c3cfb698bd405e3d3d37fc04c90e",
          "sha1": "191be71484dfaabfebba24d12686483a4647c52a",
          "md5": "933467f39de3aaed33d80b11bdd87baa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-2.1.0-beta-sources.jar",
          "url": "remote-2.1.0-beta-sources.jar",
          "size": 10025,
          "sha512": "6d13c62d3509a9b587f03192ff46f360850d118e044caaaa62be734e903c28e02760fb709b6b424bb7b5b462c94963eb7aad1a3fda4ddbade33af477e4d38a4f",
          "sha256": "f2bd95ab612cfc338de36c657a90a339b7d903a3c6a921f7eb8438446ed0d006",
          "sha1": "725796804d779036cec30aefdb75f404e05e7981",
          "md5": "d4b7672aee4774d24e3ec0cc0e55947b"
        }
      ]
    }
  ]
}
