{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.25.aar",
          "url": "logging-0.0.25.aar",
          "size": 61921,
          "sha512": "622ecdc8c29474e6fcb6d12b7cf81fd46efe3c57dceb5f9a41cda36e9eb09d1388844211b5021d20b2d52523b506867e47efbdabb1b95433583af2a293875a75",
          "sha256": "0836cc3515eb31dbefa39b7a7a289605d865cded6e1e7a840977246b974eb74e",
          "sha1": "9387b3939e753120ae87ade30499346ec5e175df",
          "md5": "ef6495dbb7e7ed45d5fbe54972ceae39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.25.aar",
          "url": "logging-0.0.25.aar",
          "size": 61921,
          "sha512": "622ecdc8c29474e6fcb6d12b7cf81fd46efe3c57dceb5f9a41cda36e9eb09d1388844211b5021d20b2d52523b506867e47efbdabb1b95433583af2a293875a75",
          "sha256": "0836cc3515eb31dbefa39b7a7a289605d865cded6e1e7a840977246b974eb74e",
          "sha1": "9387b3939e753120ae87ade30499346ec5e175df",
          "md5": "ef6495dbb7e7ed45d5fbe54972ceae39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-0.0.25-sources.jar",
          "url": "logging-0.0.25-sources.jar",
          "size": 24325,
          "sha512": "ce4ddd191062088e7e9535e4cfb987b7c2d7d60fadeb7eced1622be9508f0f46643fbc337bc317db276fc84a835192737b77d9a9cd0168315a31711cc35db07c",
          "sha256": "f434781eb7b3c9c6807538555c8d2d5d5648200b92be67b553bf57a4644838ba",
          "sha1": "e12d8d59a9c71142c76481906663cc61413bec27",
          "md5": "39979ccb1cb4faa74898bc2a7dc7227f"
        }
      ]
    }
  ]
}
