{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "1.0.2-rn-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.2-rn-3.aar",
          "url": "logging-1.0.2-rn-3.aar",
          "size": 74036,
          "sha512": "cd19f213efd3115d0980a4192adc482dc41ffbf650587d8d8d10d17005aacb3f379f823d5ade3be18b5fd0fa512426c46773c1b466b0112a8b29700aa847f3f8",
          "sha256": "8a56f41ba857ea41cf23659eb4f879da8e73b1f4304820c30b7f8f58668768a8",
          "sha1": "f50db844c0fb37e87e0aa6223565f7274ad0ebae",
          "md5": "f84c7893620ada104e98a9c3662d1ea6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.2-rn-3"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.2-rn-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.2-rn-3.aar",
          "url": "logging-1.0.2-rn-3.aar",
          "size": 74036,
          "sha512": "cd19f213efd3115d0980a4192adc482dc41ffbf650587d8d8d10d17005aacb3f379f823d5ade3be18b5fd0fa512426c46773c1b466b0112a8b29700aa847f3f8",
          "sha256": "8a56f41ba857ea41cf23659eb4f879da8e73b1f4304820c30b7f8f58668768a8",
          "sha1": "f50db844c0fb37e87e0aa6223565f7274ad0ebae",
          "md5": "f84c7893620ada104e98a9c3662d1ea6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.0.2-rn-3-sources.jar",
          "url": "logging-1.0.2-rn-3-sources.jar",
          "size": 24106,
          "sha512": "35a5bdc1871d34733f76f0d2cdc86c998ae13a892cfaeed5ccc3cb1cab8ed0f4f2ce7341384a813891aeab630ba1c44e800f617dad299584f51a41a76cc022fd",
          "sha256": "e7b89e4ed7ebd774edd584129fe0add8cca71acc27a330629f49cd179d61b1b7",
          "sha1": "af07edc7a0324c3cf441bff37af2b824e25bab5c",
          "md5": "8f3b06bf63607b58c22c50a18ff1236a"
        }
      ]
    }
  ]
}
