{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "iproovsdk",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "iproovsdk-0.0.24.aar",
          "url": "iproovsdk-0.0.24.aar",
          "size": 253359,
          "sha512": "73b760503e05b168413a15ac88079edae5dafffe0244a389b60e472bf1c576f16e46b2d7f4443979ab1c2e2312f6eb701dfff2af1766c88778f2fc7e6c1d5b23",
          "sha256": "6a5d659c357cc955432e4a0196ca8c751695edc1d2e3cf034413fd239c96173e",
          "sha1": "e3dcc58924c171580351a9d39c84349cfda6c237",
          "md5": "0f52361822a2c92463220e741d958780"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "iproovsdk-0.0.24.aar",
          "url": "iproovsdk-0.0.24.aar",
          "size": 253359,
          "sha512": "73b760503e05b168413a15ac88079edae5dafffe0244a389b60e472bf1c576f16e46b2d7f4443979ab1c2e2312f6eb701dfff2af1766c88778f2fc7e6c1d5b23",
          "sha256": "6a5d659c357cc955432e4a0196ca8c751695edc1d2e3cf034413fd239c96173e",
          "sha1": "e3dcc58924c171580351a9d39c84349cfda6c237",
          "md5": "0f52361822a2c92463220e741d958780"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iproovsdk-0.0.24-sources.jar",
          "url": "iproovsdk-0.0.24-sources.jar",
          "size": 29613,
          "sha512": "90b990ed5bd42b8ab3623eba366d39bda889c25cfc3505db35a7c4ecd6584d1c19defe8490b2ecc82a5eca649426a474bcd5acd0e8a4036b8f8583e31d0d2538",
          "sha256": "a9e557446d772d3f3cf1565f482ecfbba790e12b1ed72fa7d187aa3099e1b329",
          "sha1": "0d30cf3f8715d8749b5133e03659872e52ccd614",
          "md5": "3f5b60e8a0eb52ea1173d66aa24d3f68"
        }
      ]
    }
  ]
}
