{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "facetecsdk",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.79"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-0.0.23.aar",
          "url": "facetecsdk-0.0.23.aar",
          "size": 410757,
          "sha512": "df1887e3d514dcfb6b40adac2e3d1f01b00826991b912922c919ce8ce61eb848c296655f78a9c5e005956e3d6427b86e5510859fae75223b3738d01928b6bb6a",
          "sha256": "242ab84626956e7a4adb754f047397a2a8fd06af037f2d8f396aeb5c9cad9592",
          "sha1": "20a513a5bb3f9a9c1f85c05729ed793ab15abcec",
          "md5": "f66827bee6c73f1e5cafecf18b17689c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.79"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-0.0.23.aar",
          "url": "facetecsdk-0.0.23.aar",
          "size": 410757,
          "sha512": "df1887e3d514dcfb6b40adac2e3d1f01b00826991b912922c919ce8ce61eb848c296655f78a9c5e005956e3d6427b86e5510859fae75223b3738d01928b6bb6a",
          "sha256": "242ab84626956e7a4adb754f047397a2a8fd06af037f2d8f396aeb5c9cad9592",
          "sha1": "20a513a5bb3f9a9c1f85c05729ed793ab15abcec",
          "md5": "f66827bee6c73f1e5cafecf18b17689c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "facetecsdk-0.0.23-sources.jar",
          "url": "facetecsdk-0.0.23-sources.jar",
          "size": 69832,
          "sha512": "1a2de845669e223d54f32b5ca005c830b5a00a23e0e25390ec924aae10f051ac41b2fea25ff7e872404f6cf86054e190ea39161f2cc474e849bfaf1fe6555690",
          "sha256": "b8138748a37a719e7f609dc5423718dd57bdd05f045ea4a93712fbc1d08159bf",
          "sha1": "4ddd627b66fe1f93341fcc64cf66d883da0aeefc",
          "md5": "b157c4c27f8f012b4e4504c1d10d0460"
        }
      ]
    }
  ]
}
