{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.23.aar",
          "url": "remote-0.0.23.aar",
          "size": 12600,
          "sha512": "0a6308370f32022437502764e91a637ef06763a0c5a7e0a7db74d60c19ae82040a85efdc30771e25c299e6eae65b54b97f7beea80e4ae3fc2f380c0c0cb46f0b",
          "sha256": "05fffcd0fdc4ad0c88baabacae0ac53fcc1ff8b62faef00ec86d788b8b7d3e7d",
          "sha1": "f1d98b536512bd0f28942ca56005ce272019b640",
          "md5": "72d33369b4907215073753d64b1b8339"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.23.aar",
          "url": "remote-0.0.23.aar",
          "size": 12600,
          "sha512": "0a6308370f32022437502764e91a637ef06763a0c5a7e0a7db74d60c19ae82040a85efdc30771e25c299e6eae65b54b97f7beea80e4ae3fc2f380c0c0cb46f0b",
          "sha256": "05fffcd0fdc4ad0c88baabacae0ac53fcc1ff8b62faef00ec86d788b8b7d3e7d",
          "sha1": "f1d98b536512bd0f28942ca56005ce272019b640",
          "md5": "72d33369b4907215073753d64b1b8339"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-0.0.23-sources.jar",
          "url": "remote-0.0.23-sources.jar",
          "size": 10867,
          "sha512": "aaf7c6d97390eabd7b2a5edeed36cec0f4d8780ebe3ad777cc1eef8938a5e993fd614b560e36ba625a8f8731de55018983c261b3e2dcb7b0d3acefc8434e9863",
          "sha256": "2e513669c28bde2cf3107352fe6799460c86b0a554812cb4015916fb74bb3098",
          "sha1": "e3504387db295062d251b2d05c9978232d3ebf7e",
          "md5": "1d6aca517772bf2a591147b82ea5e63c"
        }
      ]
    }
  ]
}
