{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.27.aar",
          "url": "oiti-network-0.0.27.aar",
          "size": 43109,
          "sha512": "77c23a7b55203483f260d095f7d0b9ef3cca8364ddebccd8b2b6f803a9f7b7da6a614b792cedf0985504073d0565a545cfc017900111fe5d903412f3905efd4b",
          "sha256": "ede26e77a8b2f45491c8b0872a38c98d5a99f98947001d02711e2fcd1c3c821c",
          "sha1": "8c83fef960d44dac9ae918b2fb3115a07f460fc1",
          "md5": "06563dda5e3049aa00945b9a98e03467"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.27.aar",
          "url": "oiti-network-0.0.27.aar",
          "size": 43109,
          "sha512": "77c23a7b55203483f260d095f7d0b9ef3cca8364ddebccd8b2b6f803a9f7b7da6a614b792cedf0985504073d0565a545cfc017900111fe5d903412f3905efd4b",
          "sha256": "ede26e77a8b2f45491c8b0872a38c98d5a99f98947001d02711e2fcd1c3c821c",
          "sha1": "8c83fef960d44dac9ae918b2fb3115a07f460fc1",
          "md5": "06563dda5e3049aa00945b9a98e03467"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-0.0.27-sources.jar",
          "url": "oiti-network-0.0.27-sources.jar",
          "size": 14122,
          "sha512": "fb5b12c68f1516138695dfbe3ff0887e41201acb193d32b4617ef3813c82da3b0d81e636a644a07c9bd0d9e86d10787e5927c27701ba98d9e3d6d21020069ad7",
          "sha256": "dc9f5a40742c83eef50320bb04f6f50ffecd45cd0b2864457d6e90ab5db947c3",
          "sha1": "e4701447aab81722a398260d5150e8a53c4b602f",
          "md5": "502db0fb69195cfffd460750ad5c1ea6"
        }
      ]
    }
  ]
}
