{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "0.0.20-layout-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.20-layout-fix.aar",
          "url": "oiti-network-0.0.20-layout-fix.aar",
          "size": 39226,
          "sha512": "2cd1de25083a5bfd226b41280330f0a58791fb11d7e18560d263923c49d65ceb062cc88eacd5d71b20be0fc54225313fcd601ea82d1d1ee414c348c2af23ec33",
          "sha256": "6dbcabaf10f30f5f9aa9cd98d32eb68dd954a57928669b18af7baa3c244c943f",
          "sha1": "bf299ed228fa2dfc8640aefd4b6f44336bc9a36c",
          "md5": "3902c7d4ce8c69e82e1cb42ccc90e0fc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.20-layout-fix.aar",
          "url": "oiti-network-0.0.20-layout-fix.aar",
          "size": 39226,
          "sha512": "2cd1de25083a5bfd226b41280330f0a58791fb11d7e18560d263923c49d65ceb062cc88eacd5d71b20be0fc54225313fcd601ea82d1d1ee414c348c2af23ec33",
          "sha256": "6dbcabaf10f30f5f9aa9cd98d32eb68dd954a57928669b18af7baa3c244c943f",
          "sha1": "bf299ed228fa2dfc8640aefd4b6f44336bc9a36c",
          "md5": "3902c7d4ce8c69e82e1cb42ccc90e0fc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "oiti-network-0.0.20-layout-fix-sources.jar",
          "url": "oiti-network-0.0.20-layout-fix-sources.jar",
          "size": 22859,
          "sha512": "6fa403f50e2260ead7704eecc0587188f49d728278b0b3edfeb04d45ed9dbd3a16b1360a0e7e7e6596cd891f8e796f7f5889d998fb7f32f11865b887e2161798",
          "sha256": "7ed77cab7eeeec9a9c3e8cd747b717bafff5db963408ff4d5cb2736d25192ca2",
          "sha1": "1f53526ce5abd267e2bd4a5afa57840f4119c357",
          "md5": "6b960624dca6a6597328bde3677f103a"
        }
      ]
    }
  ]
}
