{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "fortfacesdk",
    "version": "2.0.5-beta-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "fortfacesdk-2.0.5-beta-2.aar",
          "url": "fortfacesdk-2.0.5-beta-2.aar",
          "size": 250718,
          "sha512": "f15e68591f49a8864fc0ed20b515ab8619a0e0de57c446788238898d8f96151ee977ecea2a62ade1bc11fa2f627e525997d63582ba212a5f0a442d18794caab6",
          "sha256": "a2f8568c8098a12994c845cf8690c2dfea969e8032ad04114aab466c992d7f99",
          "sha1": "86c6d4a5a968b0182bcc39dccd16a02843bd8fd8",
          "md5": "31b1d462d5dcece9a86e5513fafe5d01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "br.com.fortface",
          "module": "fortface",
          "version": {
            "requires": "1.21.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "fortface",
              "type": "aar",
              "extension": "aar",
              "classifier": "release"
            }
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.5-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.5-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.5-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.5-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.5-beta-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.5-beta-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "fortfacesdk-2.0.5-beta-2.aar",
          "url": "fortfacesdk-2.0.5-beta-2.aar",
          "size": 250718,
          "sha512": "f15e68591f49a8864fc0ed20b515ab8619a0e0de57c446788238898d8f96151ee977ecea2a62ade1bc11fa2f627e525997d63582ba212a5f0a442d18794caab6",
          "sha256": "a2f8568c8098a12994c845cf8690c2dfea969e8032ad04114aab466c992d7f99",
          "sha1": "86c6d4a5a968b0182bcc39dccd16a02843bd8fd8",
          "md5": "31b1d462d5dcece9a86e5513fafe5d01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fortfacesdk-2.0.5-beta-2-sources.jar",
          "url": "fortfacesdk-2.0.5-beta-2-sources.jar",
          "size": 83847,
          "sha512": "b8e577d1f6ef712f2d74cb7bb6fc14ad03371a8aacdce4412bb74018a641f32c1b5bedd2c137dd90674c283bb7f2a2ac170be90c0d4ee769a58c9afbab6f5068",
          "sha256": "ac96b2967b21b51d7ab0099ae2aff8d0405a7148ce408af61d3bb9c383e7617b",
          "sha1": "5f076e3c0e8010376c2921c7eb884add409a78c7",
          "md5": "5fc6d21486903990c4da61c83bef39e2"
        }
      ]
    }
  ]
}
