{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.27.aar",
          "url": "domain-0.0.27.aar",
          "size": 151279,
          "sha512": "940b96f6632703a4e1cb17c4dbcb1b6494a70f891f86f124cbfc44649fc30eda500199db3758fd7910cbf1a8646590a17ebba07bbd9b194ca2ef8e200e4ab963",
          "sha256": "30fc6d8691f76913604883b04d94c02bcdd0ff6713a4b99450211e1db8f91fd8",
          "sha1": "7c67820b9751528e90c6c7feebade1ddc9b25a5b",
          "md5": "b0db21fa90902d65115b5f2ba8622f1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.27.aar",
          "url": "domain-0.0.27.aar",
          "size": 151279,
          "sha512": "940b96f6632703a4e1cb17c4dbcb1b6494a70f891f86f124cbfc44649fc30eda500199db3758fd7910cbf1a8646590a17ebba07bbd9b194ca2ef8e200e4ab963",
          "sha256": "30fc6d8691f76913604883b04d94c02bcdd0ff6713a4b99450211e1db8f91fd8",
          "sha1": "7c67820b9751528e90c6c7feebade1ddc9b25a5b",
          "md5": "b0db21fa90902d65115b5f2ba8622f1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-0.0.27-sources.jar",
          "url": "domain-0.0.27-sources.jar",
          "size": 32658,
          "sha512": "b1786484b5d0a3e2a827fcb01490dc6da874706ae8d96fb403ba63f65e34ae4a0f11885e4ee0feab527dde8b6b52ca9703470502f00c7f027eab138399621c80",
          "sha256": "60f75b91c2f2c76771e6226db7c636bdc9dd7195f75c5a703320afc29e298679",
          "sha1": "5b0168865ad2bb8227660be20bcf8302f2d9a5f8",
          "md5": "fe8f25f2fc469cd2ea7f42b2d90849c0"
        }
      ]
    }
  ]
}
