{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "data",
    "version": "1.1.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.1.0-snapshot-2.aar",
          "url": "data-1.1.0-snapshot-2.aar",
          "size": 190208,
          "sha512": "bab3cbc9a6b896e89a0b5a3ce7e2049a7d715d7a4585c9ca9614c2ca424679695594b8b3248742e330392f43412a6be53e55ff0db68d8c8e0be094076ac2f2a6",
          "sha256": "c5c99b6d6122fe363786d3b77b53e3ae28709800c03ceace6bc0d057201929fa",
          "sha1": "d517f70a4266c77fb5aeef33844b2faec4f510da",
          "md5": "d4e2143e224010914e73daa9aa5408d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "certiface-network",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.1.0-snapshot-2.aar",
          "url": "data-1.1.0-snapshot-2.aar",
          "size": 190208,
          "sha512": "bab3cbc9a6b896e89a0b5a3ce7e2049a7d715d7a4585c9ca9614c2ca424679695594b8b3248742e330392f43412a6be53e55ff0db68d8c8e0be094076ac2f2a6",
          "sha256": "c5c99b6d6122fe363786d3b77b53e3ae28709800c03ceace6bc0d057201929fa",
          "sha1": "d517f70a4266c77fb5aeef33844b2faec4f510da",
          "md5": "d4e2143e224010914e73daa9aa5408d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.1.0-snapshot-2-sources.jar",
          "url": "data-1.1.0-snapshot-2-sources.jar",
          "size": 21722,
          "sha512": "a30a467abcc42b00e2d95aafb0a87df537f79708d3fe872243f6db8e55c4c3bcabf45be94485948e7ee3c797bf05cd17b0580647d22f138d858b47ae07f0e042",
          "sha256": "b913ef812ebd14356e7019c719f875c9df33df2107d399849dfd2252a8a17dcb",
          "sha1": "38f04ea7a4498b8effa54c70d334e159acea6c88",
          "md5": "20f1127683a92e8c089ab2b111aaec4a"
        }
      ]
    }
  ]
}
