{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "1.0.4-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.4-snapshot-1.aar",
          "url": "oiti-network-1.0.4-snapshot-1.aar",
          "size": 23547,
          "sha512": "ec80cb16dd42747dfde41da59b7e831832d133dcd4023c82ed1f4df368972d2107806de858b72de0de07d2650604438a09ef5898a14207f4aecb890f18fb3337",
          "sha256": "898b40fd9f2af01a1bf96fa9f1232097c4003c1340fbd9dd7f2eb7d826602501",
          "sha1": "be944b22a1f1f252fdd1eeaea40c98e0e7f56bf0",
          "md5": "055015b07ee2bd006b252a3af86c8936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.4-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.4-snapshot-1.aar",
          "url": "oiti-network-1.0.4-snapshot-1.aar",
          "size": 23547,
          "sha512": "ec80cb16dd42747dfde41da59b7e831832d133dcd4023c82ed1f4df368972d2107806de858b72de0de07d2650604438a09ef5898a14207f4aecb890f18fb3337",
          "sha256": "898b40fd9f2af01a1bf96fa9f1232097c4003c1340fbd9dd7f2eb7d826602501",
          "sha1": "be944b22a1f1f252fdd1eeaea40c98e0e7f56bf0",
          "md5": "055015b07ee2bd006b252a3af86c8936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-1.0.4-snapshot-1-sources.jar",
          "url": "oiti-network-1.0.4-snapshot-1-sources.jar",
          "size": 14202,
          "sha512": "6963e88e8aeed5feb2c6340de5ca42681f53abc8032ae3a2b616c1adeae74371487b34160fbb37095e4cda5ad1fd68798d8e5e425a4cf00cf5125a11fe25274e",
          "sha256": "8f320e49e4e65e5d71e545e9d82d21cc21d843916ae78b15aa13cf86cd50b23c",
          "sha1": "b75ba34599a57f0ae2cb88a6e74c795b1a0a7cb7",
          "md5": "8ccc6cb29ad5b7c88ea7a9cbd5542a6f"
        }
      ]
    }
  ]
}
