{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "1.0.2-rn-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.2-rn-4.aar",
          "url": "oiti-network-1.0.2-rn-4.aar",
          "size": 42754,
          "sha512": "5a20b26572be1599eb0b674cb8628b8bcc3f3cabcfe3fe1b5863447e212078456dbf5f56c35075f378218b040dd42dae919436283f39526e9513b257822edc83",
          "sha256": "8ee3bec3cabb53b5ab86f65233a54f10e8fd628917a70130aa39b0b51efedade",
          "sha1": "72381e6e8f6d6eb1f7fc07e242520370e9fce2ed",
          "md5": "a88c48689d60704173115949ad02f4e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.2-rn-4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.2-rn-4.aar",
          "url": "oiti-network-1.0.2-rn-4.aar",
          "size": 42754,
          "sha512": "5a20b26572be1599eb0b674cb8628b8bcc3f3cabcfe3fe1b5863447e212078456dbf5f56c35075f378218b040dd42dae919436283f39526e9513b257822edc83",
          "sha256": "8ee3bec3cabb53b5ab86f65233a54f10e8fd628917a70130aa39b0b51efedade",
          "sha1": "72381e6e8f6d6eb1f7fc07e242520370e9fce2ed",
          "md5": "a88c48689d60704173115949ad02f4e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-1.0.2-rn-4-sources.jar",
          "url": "oiti-network-1.0.2-rn-4-sources.jar",
          "size": 14202,
          "sha512": "6963e88e8aeed5feb2c6340de5ca42681f53abc8032ae3a2b616c1adeae74371487b34160fbb37095e4cda5ad1fd68798d8e5e425a4cf00cf5125a11fe25274e",
          "sha256": "8f320e49e4e65e5d71e545e9d82d21cc21d843916ae78b15aa13cf86cd50b23c",
          "sha1": "b75ba34599a57f0ae2cb88a6e74c795b1a0a7cb7",
          "md5": "8ccc6cb29ad5b7c88ea7a9cbd5542a6f"
        }
      ]
    }
  ]
}
