{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.21.aar",
          "url": "core-0.0.21.aar",
          "size": 10691,
          "sha512": "709110ab7e0f43c365d20265bfdc514fa740ab0d7ae2aa56dfb4c5a0fe3411908b2f951203b8e59f0e4597a28f7bc898f9f8fc1f66323fc43e5a32c173eb94e7",
          "sha256": "f8b44130849668065227275357a97930f7a907acc220ffd5e11c764fc4758b56",
          "sha1": "15f70d0219c75cb428e1e386aea3605d71a4d6fa",
          "md5": "ec13b2532a8133dfa850817c64afe5e7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.21.aar",
          "url": "core-0.0.21.aar",
          "size": 10691,
          "sha512": "709110ab7e0f43c365d20265bfdc514fa740ab0d7ae2aa56dfb4c5a0fe3411908b2f951203b8e59f0e4597a28f7bc898f9f8fc1f66323fc43e5a32c173eb94e7",
          "sha256": "f8b44130849668065227275357a97930f7a907acc220ffd5e11c764fc4758b56",
          "sha1": "15f70d0219c75cb428e1e386aea3605d71a4d6fa",
          "md5": "ec13b2532a8133dfa850817c64afe5e7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.0.21-sources.jar",
          "url": "core-0.0.21-sources.jar",
          "size": 6952,
          "sha512": "d8a601ae8b1a65ce2eda65a9212b83dab5e5c3cdcd1f76a8783220ef5c8129dab8d1954bcbc37e5c6e3dfe59de5550c1523fd6f0e7f564e0c3079985feb0d536",
          "sha256": "543cfe263a44ac4753a04b6d51e910c97f31b91612ba5628ae1c2bc159e1edb4",
          "sha1": "1c97945e341dfaf1cb1cc4467f9e8a0756ad5d48",
          "md5": "7fd9c9f9d56358a3aad1073b601165ba"
        }
      ]
    }
  ]
}
