{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.24.aar",
          "url": "domain-0.0.24.aar",
          "size": 149229,
          "sha512": "3ae59cb25c3096086812cb846e836e9160709c81a54e760389bb6705b6c86dbd6932fa9f108c84889b7f841eda3fe61c7c56430dc262f5d633e926681191b5bf",
          "sha256": "d74eb1c8bc2415e486c1912fdfdaa8568250e6d9027b0d7ce8c6b4706fb348e6",
          "sha1": "9386dc7f46755fa13748134c52ebcdc8b8ff7f30",
          "md5": "7214feaf43465a197f63a23aac1d37dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.24.aar",
          "url": "domain-0.0.24.aar",
          "size": 149229,
          "sha512": "3ae59cb25c3096086812cb846e836e9160709c81a54e760389bb6705b6c86dbd6932fa9f108c84889b7f841eda3fe61c7c56430dc262f5d633e926681191b5bf",
          "sha256": "d74eb1c8bc2415e486c1912fdfdaa8568250e6d9027b0d7ce8c6b4706fb348e6",
          "sha1": "9386dc7f46755fa13748134c52ebcdc8b8ff7f30",
          "md5": "7214feaf43465a197f63a23aac1d37dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-0.0.24-sources.jar",
          "url": "domain-0.0.24-sources.jar",
          "size": 32289,
          "sha512": "4e8da76a5c4f839a7e6aa9c79e14743ebe579b3a964a6a32b411a6b3c91a204ae68dfea2c28381ad4887271d8cc900920951ed4a0cbb3bde2ec5627148de00e3",
          "sha256": "5862ed9b3affcb3d2203747f9e4d940f92e8cc4c5caca0a82f9792738eb54538",
          "sha1": "c41f5fb8057517ec1103578218250e4b997d6efb",
          "md5": "671c154639a197873f362fb3077471dd"
        }
      ]
    }
  ]
}
