{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "1.0.2-rn",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.2-rn.aar",
          "url": "logging-1.0.2-rn.aar",
          "size": 59897,
          "sha512": "58904e0c0fb5f5e8c91152102c45f71f4c438084489d89e2f58f18a1f372b623eed6280a0a61d967a1f731918013510392299b07b9dfc9e4e771cfb15f284283",
          "sha256": "1e8aacf8a58212ef393b657f3f89db18a0a47eba7c234ec413826a99c7622d8d",
          "sha1": "e3b8671e54e572b9ed562e0cc7a953c7811c692b",
          "md5": "bca1262dfd64e3fc599760070658be5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.2-rn"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.2-rn"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.2-rn.aar",
          "url": "logging-1.0.2-rn.aar",
          "size": 59897,
          "sha512": "58904e0c0fb5f5e8c91152102c45f71f4c438084489d89e2f58f18a1f372b623eed6280a0a61d967a1f731918013510392299b07b9dfc9e4e771cfb15f284283",
          "sha256": "1e8aacf8a58212ef393b657f3f89db18a0a47eba7c234ec413826a99c7622d8d",
          "sha1": "e3b8671e54e572b9ed562e0cc7a953c7811c692b",
          "md5": "bca1262dfd64e3fc599760070658be5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.0.2-rn-sources.jar",
          "url": "logging-1.0.2-rn-sources.jar",
          "size": 24106,
          "sha512": "35a5bdc1871d34733f76f0d2cdc86c998ae13a892cfaeed5ccc3cb1cab8ed0f4f2ce7341384a813891aeab630ba1c44e800f617dad299584f51a41a76cc022fd",
          "sha256": "e7b89e4ed7ebd774edd584129fe0add8cca71acc27a330629f49cd179d61b1b7",
          "sha1": "af07edc7a0324c3cf441bff37af2b824e25bab5c",
          "md5": "8f3b06bf63607b58c22c50a18ff1236a"
        }
      ]
    }
  ]
}
