{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "facetecsdk",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.81"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-0.0.25.aar",
          "url": "facetecsdk-0.0.25.aar",
          "size": 410248,
          "sha512": "0b4eaf1fa5c31a6305e7182d4c5d8801fd9e963d7b118806179d960308dd02547b05005e623529988d0533e844747d09ce0a2289a0229a5f5ccb174ccff06ddf",
          "sha256": "c8203bbf906665f448ba64687733f9b1525a1abf79b3b7ac13f4a079daa7e519",
          "sha1": "3d3c88001ac167e962336698488a4f251ba39e61",
          "md5": "5a1440e88a3d9a4a93091744654529b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.81"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-0.0.25.aar",
          "url": "facetecsdk-0.0.25.aar",
          "size": 410248,
          "sha512": "0b4eaf1fa5c31a6305e7182d4c5d8801fd9e963d7b118806179d960308dd02547b05005e623529988d0533e844747d09ce0a2289a0229a5f5ccb174ccff06ddf",
          "sha256": "c8203bbf906665f448ba64687733f9b1525a1abf79b3b7ac13f4a079daa7e519",
          "sha1": "3d3c88001ac167e962336698488a4f251ba39e61",
          "md5": "5a1440e88a3d9a4a93091744654529b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "facetecsdk-0.0.25-sources.jar",
          "url": "facetecsdk-0.0.25-sources.jar",
          "size": 38112,
          "sha512": "3d19a95a979e122134d495ca89ace52361c83da040818f0c38a4c10487ebe5f5df99e133efd106bafaedd45c5d7ddac0fdf9f43a846fb4643b3d9b7028ec95a1",
          "sha256": "d482d7bcb52f53fb5f39f4a9ed4fc3c8a5a344515f71a81845af07d4727c5c2e",
          "sha1": "7e5b19daedaad904f8f126d15536c16c8a3f638f",
          "md5": "60fdb453252d8e69e7d290030907860b"
        }
      ]
    }
  ]
}
