{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oitisdk",
    "version": "0.0.20-layout-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "facetecsdk",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.20-layout-fix.aar",
          "url": "oitisdk-0.0.20-layout-fix.aar",
          "size": 53773,
          "sha512": "8f62b3b3b05e4b57597aefb6eb6bcb90a8204b4404b632e12a89e2fb243c114933cb2dfb2c6119233ac2a095b9014d183b104bfce33e92c82e64705b8e0d2b97",
          "sha256": "221207b438332f337474f4791049987a15eed15e7e371cc1b63aec60622e2cb5",
          "sha1": "361d9a1ee61f14db2c9a78f1aada94e65a8b1540",
          "md5": "be2eb4a26f1a95630a7c6b0251d10a2f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "data",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "facetecsdk",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.20-layout-fix.aar",
          "url": "oitisdk-0.0.20-layout-fix.aar",
          "size": 53773,
          "sha512": "8f62b3b3b05e4b57597aefb6eb6bcb90a8204b4404b632e12a89e2fb243c114933cb2dfb2c6119233ac2a095b9014d183b104bfce33e92c82e64705b8e0d2b97",
          "sha256": "221207b438332f337474f4791049987a15eed15e7e371cc1b63aec60622e2cb5",
          "sha1": "361d9a1ee61f14db2c9a78f1aada94e65a8b1540",
          "md5": "be2eb4a26f1a95630a7c6b0251d10a2f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "oitisdk-0.0.20-layout-fix-sources.jar",
          "url": "oitisdk-0.0.20-layout-fix-sources.jar",
          "size": 37720,
          "sha512": "cbd06cef1ec51c0016bfa057a563729b9c74f14a9a2475010b278e560dce66cbd8b890f3aa5499d2ef8d8afaedb3691aad5c880aa3c5de5c341b8303be0c2f59",
          "sha256": "2143096dc4443c216cacc0f4b3a8d5c5a2d122f83900887d86c52eed907eed21",
          "sha1": "dc93eb9a64c34fc8721f103598ddd7ff97023df2",
          "md5": "3681db092c8abf35a381d52d60d492a1"
        }
      ]
    }
  ]
}
