{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.23.aar",
          "url": "logging-0.0.23.aar",
          "size": 57614,
          "sha512": "3eefb52c5f4ee7c6da1179728ca005ae694839d0d9532dff18c94e9f77afe7e75173117e57f41b63a963eeaf15db84f08ca2e18850fd34c6c92a0016a8b135e7",
          "sha256": "1f6b1279aead0d287c657bff8d9cda82d5f56035bcef9cb6a7563055faa1d9dd",
          "sha1": "82379d7fca5646493f25f38c0eeddd76b3c54544",
          "md5": "d864dafca07fd4cafe45659733c94852"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.23.aar",
          "url": "logging-0.0.23.aar",
          "size": 57614,
          "sha512": "3eefb52c5f4ee7c6da1179728ca005ae694839d0d9532dff18c94e9f77afe7e75173117e57f41b63a963eeaf15db84f08ca2e18850fd34c6c92a0016a8b135e7",
          "sha256": "1f6b1279aead0d287c657bff8d9cda82d5f56035bcef9cb6a7563055faa1d9dd",
          "sha1": "82379d7fca5646493f25f38c0eeddd76b3c54544",
          "md5": "d864dafca07fd4cafe45659733c94852"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logging-0.0.23-sources.jar",
          "url": "logging-0.0.23-sources.jar",
          "size": 36032,
          "sha512": "1f949bd17f910c4cba22cd563f62a8e58d566cb42ff3b71071512e103cfb511b6d51ea9cef23dfabff511997083b9df8f4f6bd298965c1486c22e8553cab5de5",
          "sha256": "1b18d66ebfb7fd1429656f770b5a8608f38041670f6de4989b02e29895ed42ca",
          "sha1": "5ce624823a7d8a5ae219f869f46eadf34f8c04e6",
          "md5": "495b8b303d8f54114789dd6b7826774b"
        }
      ]
    }
  ]
}
