{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.3.aar",
          "url": "core-1.0.3.aar",
          "size": 10815,
          "sha512": "bcf4c1947f94cf004ced431d5ba692ab36630905e88bfb6a716ca7389839edf30eb259816bc156972114f86939ac9b264481661ae9933e402330848fcf05d135",
          "sha256": "8100126219025ae4c821b7de4e04e8529538357f9681832cf2d89df660d771ea",
          "sha1": "cab7ef4b37a4692d0ae4d8092de70673eba4fc8e",
          "md5": "192df9dbfea5b8d4aa7e1c9ae51c5ecb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.3.aar",
          "url": "core-1.0.3.aar",
          "size": 10815,
          "sha512": "bcf4c1947f94cf004ced431d5ba692ab36630905e88bfb6a716ca7389839edf30eb259816bc156972114f86939ac9b264481661ae9933e402330848fcf05d135",
          "sha256": "8100126219025ae4c821b7de4e04e8529538357f9681832cf2d89df660d771ea",
          "sha1": "cab7ef4b37a4692d0ae4d8092de70673eba4fc8e",
          "md5": "192df9dbfea5b8d4aa7e1c9ae51c5ecb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.3-sources.jar",
          "url": "core-1.0.3-sources.jar",
          "size": 4283,
          "sha512": "252c0347cc16d1cc48aa3ad05d140af3cff6e33fe93b05e763dceffb02007bb7165fa1cf5aabb46948b13811f87a26180587e840bdce762e5cdd646d51b066bc",
          "sha256": "b0f4244abf2d7a9354161bef3d9ef347847b5330347712d4b94942e1d7f836c6",
          "sha1": "a788ca659e9399e49a8c8779c4b63f4a9b72d3bf",
          "md5": "317af4ef6aa26db21f3e4141b29e2e7f"
        }
      ]
    }
  ]
}
