{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.2.aar",
          "url": "oiti-network-1.0.2.aar",
          "size": 43286,
          "sha512": "f31ce7ec015be4bbdde4e8cbeeba7b2a5fcdb217f5eebb1d691c9399b50b2d3a4a84f2dd486e13b11e7c16f68ad10dd824a5482fd817fced7735fc236985df2d",
          "sha256": "3b2b1ef976cd46cca33cf7c8c271f9a8a3f7503474350d68cc885a730ec2c998",
          "sha1": "0c8bb1f8db459994b3563b5a6d13a3f1f242bb68",
          "md5": "887add9f9179248082622765fa933f67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-1.0.2.aar",
          "url": "oiti-network-1.0.2.aar",
          "size": 43286,
          "sha512": "f31ce7ec015be4bbdde4e8cbeeba7b2a5fcdb217f5eebb1d691c9399b50b2d3a4a84f2dd486e13b11e7c16f68ad10dd824a5482fd817fced7735fc236985df2d",
          "sha256": "3b2b1ef976cd46cca33cf7c8c271f9a8a3f7503474350d68cc885a730ec2c998",
          "sha1": "0c8bb1f8db459994b3563b5a6d13a3f1f242bb68",
          "md5": "887add9f9179248082622765fa933f67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-1.0.2-sources.jar",
          "url": "oiti-network-1.0.2-sources.jar",
          "size": 14202,
          "sha512": "6963e88e8aeed5feb2c6340de5ca42681f53abc8032ae3a2b616c1adeae74371487b34160fbb37095e4cda5ad1fd68798d8e5e425a4cf00cf5125a11fe25274e",
          "sha256": "8f320e49e4e65e5d71e545e9d82d21cc21d843916ae78b15aa13cf86cd50b23c",
          "sha1": "b75ba34599a57f0ae2cb88a6e74c795b1a0a7cb7",
          "md5": "8ccc6cb29ad5b7c88ea7a9cbd5542a6f"
        }
      ]
    }
  ]
}
