{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.0.aar",
          "url": "domain-1.1.0.aar",
          "size": 156711,
          "sha512": "9068d83ec07cee12117ce32c22d6c0f1ba872bb3120660c978e749e93c22742db5d8f7c05533ea4ab7d346ec2991cf42fb4a970d8a6e50842b80e48d66787cb4",
          "sha256": "df4e13ecf3a17c1d11857f7f51b8f4c6ba707ea9f3c37a71ad1364a7a70755b5",
          "sha1": "b5a7bff5a38df1f8b0968a3fdfc6115481a90f9a",
          "md5": "b55ec8e182fde58728a3302bfa2d6022"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.0.aar",
          "url": "domain-1.1.0.aar",
          "size": 156711,
          "sha512": "9068d83ec07cee12117ce32c22d6c0f1ba872bb3120660c978e749e93c22742db5d8f7c05533ea4ab7d346ec2991cf42fb4a970d8a6e50842b80e48d66787cb4",
          "sha256": "df4e13ecf3a17c1d11857f7f51b8f4c6ba707ea9f3c37a71ad1364a7a70755b5",
          "sha1": "b5a7bff5a38df1f8b0968a3fdfc6115481a90f9a",
          "md5": "b55ec8e182fde58728a3302bfa2d6022"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.1.0-sources.jar",
          "url": "domain-1.1.0-sources.jar",
          "size": 38271,
          "sha512": "930bcf71ab8db4b069706b2f2ea1357525beb52eb1a8e3fb9faed19fc5f256994364a4586b47a05f1f6e6ff1a25087cd8a5cc74b6be05bf9c1bc9f92c7e6b410",
          "sha256": "8772de40b41f99d5388bc1397bbfa012d0b5c5fde9bdaa6d009d0c6c68cef418",
          "sha1": "597178cf350f7c172f03e47c7104872aff3fe070",
          "md5": "c82cb938fddac25b45634b36479d958b"
        }
      ]
    }
  ]
}
