{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.0.aar",
          "url": "domain-1.1.0.aar",
          "size": 158900,
          "sha512": "c40f5b046d64df63a2e2fdf8aa6f37b71fb20cacb17682976dbf5e7ebd8e977740135318f7dd5290c1c545e57f618a81d891023b6b0b5ff0a253401d963c9649",
          "sha256": "12d88a938a5e5bc120798a42e3fbc92cc868b2357fec5180835712c45ae71fda",
          "sha1": "003c78ead1893bc5eb78f3fd4f737634ee961923",
          "md5": "0447006e811cebc9a0abd77be1c373fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.0.aar",
          "url": "domain-1.1.0.aar",
          "size": 158900,
          "sha512": "c40f5b046d64df63a2e2fdf8aa6f37b71fb20cacb17682976dbf5e7ebd8e977740135318f7dd5290c1c545e57f618a81d891023b6b0b5ff0a253401d963c9649",
          "sha256": "12d88a938a5e5bc120798a42e3fbc92cc868b2357fec5180835712c45ae71fda",
          "sha1": "003c78ead1893bc5eb78f3fd4f737634ee961923",
          "md5": "0447006e811cebc9a0abd77be1c373fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.1.0-sources.jar",
          "url": "domain-1.1.0-sources.jar",
          "size": 38271,
          "sha512": "930bcf71ab8db4b069706b2f2ea1357525beb52eb1a8e3fb9faed19fc5f256994364a4586b47a05f1f6e6ff1a25087cd8a5cc74b6be05bf9c1bc9f92c7e6b410",
          "sha256": "8772de40b41f99d5388bc1397bbfa012d0b5c5fde9bdaa6d009d0c6c68cef418",
          "sha1": "597178cf350f7c172f03e47c7104872aff3fe070",
          "md5": "c82cb938fddac25b45634b36479d958b"
        }
      ]
    }
  ]
}
