{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "certifacesdk",
    "version": "1.1.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-1.1.0-snapshot-2.aar",
          "url": "certifacesdk-1.1.0-snapshot-2.aar",
          "size": 96485,
          "sha512": "0bed7b8a2f0e77e6ed6fc48034fd3befc3868dde44cc3d534f5412bd8940a8f4805bee30f9271270d027e40b4900144784869bbda5193ac374b55991c4b298bc",
          "sha256": "1d9013378d7263b39cdfe66a6d99752e34a37a031716aad79f09c9f36137c7c6",
          "sha1": "9ad5c8b207fbf6b7edcb3b5ca5946b71310f5c71",
          "md5": "96aacdfe0d7057b1068d83013745a108"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "remote",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "certiface-network",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "iproovsdk",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "facetecsdk",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "certifacesdk-1.1.0-snapshot-2.aar",
          "url": "certifacesdk-1.1.0-snapshot-2.aar",
          "size": 96485,
          "sha512": "0bed7b8a2f0e77e6ed6fc48034fd3befc3868dde44cc3d534f5412bd8940a8f4805bee30f9271270d027e40b4900144784869bbda5193ac374b55991c4b298bc",
          "sha256": "1d9013378d7263b39cdfe66a6d99752e34a37a031716aad79f09c9f36137c7c6",
          "sha1": "9ad5c8b207fbf6b7edcb3b5ca5946b71310f5c71",
          "md5": "96aacdfe0d7057b1068d83013745a108"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "certifacesdk-1.1.0-snapshot-2-sources.jar",
          "url": "certifacesdk-1.1.0-snapshot-2-sources.jar",
          "size": 38345,
          "sha512": "cd0686222c99f01e1615971bcc1783d472adbd305368e96adf66a8ca4e4c067f67dc7f0144acfa6b4cd0e0ebf5d0ef31374a294315e3f23c80f7f682c727fd48",
          "sha256": "c9bff517317842329cc2a6e8f8c7c7146096c6bcfe275f9b74e424662a8bf8f2",
          "sha1": "30344aab2b21fdc312e954195ccfbbbcbf7e95ae",
          "md5": "1d3c62f61e0baed41fb50ec92ed8be0e"
        }
      ]
    }
  ]
}
