{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "1.1.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.1.0-snapshot.aar",
          "url": "designsystem-1.1.0-snapshot.aar",
          "size": 1886260,
          "sha512": "199e48b86062446217062ac9dfd06d9ed96fca0e647ac3cbe92a7ce45b8e7d1c106a81ba0f13330989b5ddd56c34b4e63e06ea69f26af16bb9f32981b73385b8",
          "sha256": "34df2ee7d25c6d91e436f3552d46654f23a7f9dd9d7c7420a716d1b8b70a1ae8",
          "sha1": "e5292736c0c83d0c878761ed9d727476e8191d66",
          "md5": "ecb7d9969ff97f55501193137e76b70b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.1.0-snapshot.aar",
          "url": "designsystem-1.1.0-snapshot.aar",
          "size": 1886260,
          "sha512": "199e48b86062446217062ac9dfd06d9ed96fca0e647ac3cbe92a7ce45b8e7d1c106a81ba0f13330989b5ddd56c34b4e63e06ea69f26af16bb9f32981b73385b8",
          "sha256": "34df2ee7d25c6d91e436f3552d46654f23a7f9dd9d7c7420a716d1b8b70a1ae8",
          "sha1": "e5292736c0c83d0c878761ed9d727476e8191d66",
          "md5": "ecb7d9969ff97f55501193137e76b70b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.1.0-snapshot-sources.jar",
          "url": "designsystem-1.1.0-snapshot-sources.jar",
          "size": 33744,
          "sha512": "f0467c31a63d0e87eebf4ecce6b832aaa867aa41439529b0b7a6ffdf033117fb22524b936725dee22aa37e830ed7e751cff5346ccb8ae94fe8dfcca9e2804724",
          "sha256": "5a4966802406728aad614108b5145b9d960d8c91f0a5c0c46ec57948cca33e05",
          "sha1": "5fae8375e6fcc6ba9303dd516031f54de54f2629",
          "md5": "07469008bd73d62c9c6c1f73a78a02eb"
        }
      ]
    }
  ]
}
