{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "2.1.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-2.1.0-beta.aar",
          "url": "domain-2.1.0-beta.aar",
          "size": 318656,
          "sha512": "c8ac034dc20fc9a2672c9a69e48ab3b294da32e95bdf4c1be72ce3dcf252633645ccb9f27ac10a51eeca4f90b3f608462565f740116b6f1f12e4b4838ba4e811",
          "sha256": "b463777dc339b92d2a9553189ed95c79033941ba9ea84d6ec6022d99c5718ec9",
          "sha1": "74a16c407a0245cf28f72b928423fa9b96ba79b3",
          "md5": "1da2d85cace7595e6f4939a72801d692"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.1.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-2.1.0-beta.aar",
          "url": "domain-2.1.0-beta.aar",
          "size": 318656,
          "sha512": "c8ac034dc20fc9a2672c9a69e48ab3b294da32e95bdf4c1be72ce3dcf252633645ccb9f27ac10a51eeca4f90b3f608462565f740116b6f1f12e4b4838ba4e811",
          "sha256": "b463777dc339b92d2a9553189ed95c79033941ba9ea84d6ec6022d99c5718ec9",
          "sha1": "74a16c407a0245cf28f72b928423fa9b96ba79b3",
          "md5": "1da2d85cace7595e6f4939a72801d692"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-2.1.0-beta-sources.jar",
          "url": "domain-2.1.0-beta-sources.jar",
          "size": 71181,
          "sha512": "681c3438228acd0c5052e891bbe8ab18ae6c14cb1226c5f25c305e739ab0ea0bd2b0f09ea7908ac609e18d51cd6649f8bef904c00d4925a5765409e605e809d2",
          "sha256": "9b7f08ddd80917b8d78a10f56ee5ded0b099b16de37bf824167d0a31eb9f9742",
          "sha1": "efc552e4b7efd5c86493e91bbb7f734ca3492e8a",
          "md5": "64a13be9eeae13f4997648d9d56bded4"
        }
      ]
    }
  ]
}
