{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.24.aar",
          "url": "logging-0.0.24.aar",
          "size": 61217,
          "sha512": "d2fe19ac8ccde8f62c8587e7add2a7a15f074bc7fb129cee632ec968534207d94effd8c8bfd051d742f0249e0f42c7bfc0ce6080af12a2165fdaed76327b6ba7",
          "sha256": "5ba49f2caab75ad1c1f7a5ef42142e96f796825ebe7bf861e88e5f6406b918a8",
          "sha1": "3cfe60ea205f7c4a0b9e9ea22cbceaa55b59f9ec",
          "md5": "ddc8243e039d385daf75fe9149ef1b93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.24.aar",
          "url": "logging-0.0.24.aar",
          "size": 61217,
          "sha512": "d2fe19ac8ccde8f62c8587e7add2a7a15f074bc7fb129cee632ec968534207d94effd8c8bfd051d742f0249e0f42c7bfc0ce6080af12a2165fdaed76327b6ba7",
          "sha256": "5ba49f2caab75ad1c1f7a5ef42142e96f796825ebe7bf861e88e5f6406b918a8",
          "sha1": "3cfe60ea205f7c4a0b9e9ea22cbceaa55b59f9ec",
          "md5": "ddc8243e039d385daf75fe9149ef1b93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-0.0.24-sources.jar",
          "url": "logging-0.0.24-sources.jar",
          "size": 24042,
          "sha512": "c79afdacd03ba92850a27a7b37e10025299eb8449ab5825a5337dfb0a292e3a9fa518a5341548f6fdedaf8e2dd5af6f3e01093de16841b35b212468d4cc6c839",
          "sha256": "a8120ec4abd3bc6073d6c8d5a808bb3f164fca91d4599a57c1cab25039aeb730",
          "sha1": "c7c93f770e4e11f4d437abd79086af3c08ce51e1",
          "md5": "8eb1bf525e8c335321e8c3e1265b5851"
        }
      ]
    }
  ]
}
