{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "0.0.20-layout-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.20-layout-fix.aar",
          "url": "designsystem-0.0.20-layout-fix.aar",
          "size": 1939822,
          "sha512": "c447e1c0e6e7539643876923a0135ca5c2d736eec44d190db259822264528e396afe13cbe644ed32d5c89e239de3b90fd3ff35e361bb82451d3696236dd9175a",
          "sha256": "1f7fad37ddfbdf597c043a328b3ada123a598b964d453c4fb5aaf161f4290bf5",
          "sha1": "9a90a3a141afc9292a67bdf60f97354bb0cb3a50",
          "md5": "afed4550cf279331922dae9cead4413f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.20-layout-fix.aar",
          "url": "designsystem-0.0.20-layout-fix.aar",
          "size": 1939822,
          "sha512": "c447e1c0e6e7539643876923a0135ca5c2d736eec44d190db259822264528e396afe13cbe644ed32d5c89e239de3b90fd3ff35e361bb82451d3696236dd9175a",
          "sha256": "1f7fad37ddfbdf597c043a328b3ada123a598b964d453c4fb5aaf161f4290bf5",
          "sha1": "9a90a3a141afc9292a67bdf60f97354bb0cb3a50",
          "md5": "afed4550cf279331922dae9cead4413f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "designsystem-0.0.20-layout-fix-sources.jar",
          "url": "designsystem-0.0.20-layout-fix-sources.jar",
          "size": 53679,
          "sha512": "2046ac6adf7ca20f14b25c2d575526641c655791f18a20bc24d08682dcf83e50b5c3bc48082fdaedaa75bcf7103dd36cef73bebdcda88a06039e4e1c26b1d825",
          "sha256": "b4d5c19b34baef0aa212e853982eefc5739a70b29e35316bc6d38bc504fb262f",
          "sha1": "4781159002443b4fc73b5647492937a11332592c",
          "md5": "7074ed2a0b7be2a71d2f1667c6d21407"
        }
      ]
    }
  ]
}
