{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "1.0.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0-snapshot-2.aar",
          "url": "domain-1.0.0-snapshot-2.aar",
          "size": 150808,
          "sha512": "d717d05668832a37900dddd6ebc2d5e7c28a77ffae49734b24eae8287f879881271dc2e294183949d111a50ecb95a93f9428750e9201852f4d2f16cf2918ae80",
          "sha256": "6a2a2852eb8769de8bec0bdac4440f42c5b6ba0dcf360c61851b4e5d793a89b1",
          "sha1": "dae0d2b116fa1206dff88794044c28566587d800",
          "md5": "7f37bfc3bd21975fbaba59fc2502680b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0-snapshot-2.aar",
          "url": "domain-1.0.0-snapshot-2.aar",
          "size": 150808,
          "sha512": "d717d05668832a37900dddd6ebc2d5e7c28a77ffae49734b24eae8287f879881271dc2e294183949d111a50ecb95a93f9428750e9201852f4d2f16cf2918ae80",
          "sha256": "6a2a2852eb8769de8bec0bdac4440f42c5b6ba0dcf360c61851b4e5d793a89b1",
          "sha1": "dae0d2b116fa1206dff88794044c28566587d800",
          "md5": "7f37bfc3bd21975fbaba59fc2502680b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.0.0-snapshot-2-sources.jar",
          "url": "domain-1.0.0-snapshot-2-sources.jar",
          "size": 32704,
          "sha512": "b199daae0fe4b2af82dfbbfa19ad63b52469f2edd89b3e926128c7ee9536a7c88dee556f2d6ad34d43abe355d7e4206d8257b1224b56fe9be252bcf3e5fd91c2",
          "sha256": "970b179682557de6e871789daeb8505647d029f2b4019ef64b476c24ba2ccde1",
          "sha1": "87da27704a0b1c851c3f961c24276591a099795b",
          "md5": "4452b292c3ec74734ff243434de44578"
        }
      ]
    }
  ]
}
