{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "network",
    "version": "2.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.0.4-beta.aar",
          "url": "network-2.0.4-beta.aar",
          "size": 33573,
          "sha512": "2e90340853fceafedb2c3e0b12be11872f55477fe5d39d15be54f5e44cfa4a93c3c4735759071f299d0dc3a5c4a6ac229e3c5b69703e3fd3a1c34b9154569338",
          "sha256": "cc455956837e14508b320a386b84c3520858497f7ba0cba90464302fe657ba59",
          "sha1": "f8680b8b2b20b61eb91ad2210bc735f10c5d18bb",
          "md5": "f350d44af47919bc2cd7305a04c2778e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.0.4-beta.aar",
          "url": "network-2.0.4-beta.aar",
          "size": 33573,
          "sha512": "2e90340853fceafedb2c3e0b12be11872f55477fe5d39d15be54f5e44cfa4a93c3c4735759071f299d0dc3a5c4a6ac229e3c5b69703e3fd3a1c34b9154569338",
          "sha256": "cc455956837e14508b320a386b84c3520858497f7ba0cba90464302fe657ba59",
          "sha1": "f8680b8b2b20b61eb91ad2210bc735f10c5d18bb",
          "md5": "f350d44af47919bc2cd7305a04c2778e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "network-2.0.4-beta-sources.jar",
          "url": "network-2.0.4-beta-sources.jar",
          "size": 17956,
          "sha512": "54756a0531c4d0254a812e40eb680152984730a768dcae0bbf671692133347df9485d7e97242cec8034b975d965baebb2b6dfbbc718f190dbd78af05ccbda635",
          "sha256": "df496349b354ed5ebbcca7e0857576192023310825e5a7d135b9a4b082b6ae06",
          "sha1": "b533e70329df5a66bcdf2e2f4420669b6ec3872a",
          "md5": "649935e2701c47897576ebfb0b7c5011"
        }
      ]
    }
  ]
}
