{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.22.aar",
          "url": "core-0.0.22.aar",
          "size": 10776,
          "sha512": "2e3a30df3958af581eccef0d71f2ea8a3cd3285de12b4eb92ec61c8dac90271e9a595f75d3571899581d31e81105df005fad2e7bb678e213b109f4295537b6fe",
          "sha256": "655a7aa024433d6564059d6659cc2d06a078b270a4190b3eed3b3bb320293fe1",
          "sha1": "f2eb4919782ac338d032ddedfb11a1eb45f4c011",
          "md5": "112ddf93ff133c752145a68b595995a1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.22.aar",
          "url": "core-0.0.22.aar",
          "size": 10776,
          "sha512": "2e3a30df3958af581eccef0d71f2ea8a3cd3285de12b4eb92ec61c8dac90271e9a595f75d3571899581d31e81105df005fad2e7bb678e213b109f4295537b6fe",
          "sha256": "655a7aa024433d6564059d6659cc2d06a078b270a4190b3eed3b3bb320293fe1",
          "sha1": "f2eb4919782ac338d032ddedfb11a1eb45f4c011",
          "md5": "112ddf93ff133c752145a68b595995a1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.0.22-sources.jar",
          "url": "core-0.0.22-sources.jar",
          "size": 6974,
          "sha512": "b563a281858f915a8f89b51980c4659d3507c133babeaaedc07bd0418f6865302f61b7abe42ac75264da847faa4e41a5091f1f8acfce0f505c00edd7e8416e6b",
          "sha256": "3884d72d15f92460a06182809e3ef4ec44dca99e3fd5f4182b64cefebb044a70",
          "sha1": "5b8865f7bdd325ce54a5c012e72ffd09a4e4efb9",
          "md5": "dfbf93d5fe566479532850cb5d669411"
        }
      ]
    }
  ]
}
