{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.1.aar",
          "url": "domain-1.1.1.aar",
          "size": 158417,
          "sha512": "193591920e0b385066a4af118d32518ab96501baff811f544716a340f14c920c86aff7474279498c5452e640302e15af5754ff535fd7dd7de55dd07f320d724d",
          "sha256": "aa40376fa5381bb9490538a379c822ef538f195aec8328dd6854ec412114c660",
          "sha1": "e90c13c7e8dd83e0f86624a1641c0e9b16f0a143",
          "md5": "5d55f292f3348bb1e2e0ddd795a130ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.1.aar",
          "url": "domain-1.1.1.aar",
          "size": 158417,
          "sha512": "193591920e0b385066a4af118d32518ab96501baff811f544716a340f14c920c86aff7474279498c5452e640302e15af5754ff535fd7dd7de55dd07f320d724d",
          "sha256": "aa40376fa5381bb9490538a379c822ef538f195aec8328dd6854ec412114c660",
          "sha1": "e90c13c7e8dd83e0f86624a1641c0e9b16f0a143",
          "md5": "5d55f292f3348bb1e2e0ddd795a130ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.1.1-sources.jar",
          "url": "domain-1.1.1-sources.jar",
          "size": 38267,
          "sha512": "a0a76413b2c3ef5baf65b3388c115180a19e2b4e681104900f6747c94ba69a85530de585d2d92ba69d4e863488152d7728ce00194165f65928b4f0674bebc71b",
          "sha256": "53fc1a32194335c4940e82ab4ea6e5ac7f0245a223ed740f232d3de0b6d0976e",
          "sha1": "789efc22fbd070120b7291f6bb4d8f0c3d7f54c1",
          "md5": "2cac6b036308a6833c29efb8c726d479"
        }
      ]
    }
  ]
}
