{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.24.aar",
          "url": "core-0.0.24.aar",
          "size": 11511,
          "sha512": "8f7e980dacc5040ff6a12db0ba3e3453c4f3eb5d5311ffab89f91adba1584803bfa25779c268d039c80a79d2a33f4f818afec3ce04466f82d39c889f01579bd9",
          "sha256": "22fed0d43ea8ddc1733c2e635d368a8ac957f3f932cb86130ebbf93888c49b87",
          "sha1": "4ae30102c6ddc007fec1c52b6a5d564d0c5892cd",
          "md5": "3f96944820a654d4e5f57d1c04fcae51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.24.aar",
          "url": "core-0.0.24.aar",
          "size": 11511,
          "sha512": "8f7e980dacc5040ff6a12db0ba3e3453c4f3eb5d5311ffab89f91adba1584803bfa25779c268d039c80a79d2a33f4f818afec3ce04466f82d39c889f01579bd9",
          "sha256": "22fed0d43ea8ddc1733c2e635d368a8ac957f3f932cb86130ebbf93888c49b87",
          "sha1": "4ae30102c6ddc007fec1c52b6a5d564d0c5892cd",
          "md5": "3f96944820a654d4e5f57d1c04fcae51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.0.24-sources.jar",
          "url": "core-0.0.24-sources.jar",
          "size": 4246,
          "sha512": "ede784e2d3a0263e84d5f8fe1169fde52c81887cb452ea78aa75dbf1033ccca7b7bf7694415cacb1c9155dcb4fe0a817a9f680cca115b095c778d0cfd139ced5",
          "sha256": "93e7cc7e05a731b84f0deb75837023c098758c66640ed8a533bc62576e68bca3",
          "sha1": "b607e9a7baa85b1be0e6f216537b566e3cf3a713",
          "md5": "7bd45914b18fd026b492ac9a95bfcd26"
        }
      ]
    }
  ]
}
