{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.20.aar",
          "url": "utils-0.0.20.aar",
          "size": 68565,
          "sha512": "ca88e064ad6892651194325496fcae2f81bd018ba05350f7b873ff5a81d696ddcadba9e246d59f947fad4ee722f8f3740fec506a57d47d1e7efe528ccc68fcc5",
          "sha256": "14b1ea898e1015982d6a24bc043fb847fbcddeafcca5090178412233df5baf39",
          "sha1": "7eafa6ff997ec5d3e1a3face7f947ff986b8be5f",
          "md5": "cc172bed6009816043f0e5658e1b6725"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.56.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.20.aar",
          "url": "utils-0.0.20.aar",
          "size": 68565,
          "sha512": "ca88e064ad6892651194325496fcae2f81bd018ba05350f7b873ff5a81d696ddcadba9e246d59f947fad4ee722f8f3740fec506a57d47d1e7efe528ccc68fcc5",
          "sha256": "14b1ea898e1015982d6a24bc043fb847fbcddeafcca5090178412233df5baf39",
          "sha1": "7eafa6ff997ec5d3e1a3face7f947ff986b8be5f",
          "md5": "cc172bed6009816043f0e5658e1b6725"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.20-sources.jar",
          "url": "utils-0.0.20-sources.jar",
          "size": 37974,
          "sha512": "a74870acd1ed5c72cf704d1432bb107cb35f1dafd21ac33aad24f66c65581eee3d4280db528ab886523c6724ff3b4dde56252dcae5ca1315e5eb33bdce6e9388",
          "sha256": "24182c82150d7eed56b15acfcfa9c9e625d146d56e0008e45b85a7cd3d5dc88d",
          "sha1": "865d4f78e4a31c4d43a81fa3ae013f3d80ad1239",
          "md5": "8bb6b7d3240206cf9f996a51a46ee53e"
        }
      ]
    }
  ]
}
