{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.27.aar",
          "url": "data-0.0.27.aar",
          "size": 198117,
          "sha512": "b3d48322df4fe9b79624216bc9d52fe8dd4a8d6d6aad5dfeec5bec66f0dcf83328f6f68191db5eb152490ee3aff935499059f73776c6bd3e7dc4a799af9d6609",
          "sha256": "de680fc0eb83f615e881351d1a0b5588d90b720effb063c04282429aa65364e2",
          "sha1": "52ff82d6171958d7761a196771f825dc7a25b208",
          "md5": "d7ee53f538381b5bb44016261ac3d9b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.27.aar",
          "url": "data-0.0.27.aar",
          "size": 198117,
          "sha512": "b3d48322df4fe9b79624216bc9d52fe8dd4a8d6d6aad5dfeec5bec66f0dcf83328f6f68191db5eb152490ee3aff935499059f73776c6bd3e7dc4a799af9d6609",
          "sha256": "de680fc0eb83f615e881351d1a0b5588d90b720effb063c04282429aa65364e2",
          "sha1": "52ff82d6171958d7761a196771f825dc7a25b208",
          "md5": "d7ee53f538381b5bb44016261ac3d9b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-0.0.27-sources.jar",
          "url": "data-0.0.27-sources.jar",
          "size": 19357,
          "sha512": "aaae220d0bca9566f42fff5560425c79795e7b3e68fe51db1eaa722bff94b8acef7944985e982b2a2c82cace08212a0f56300b115c81299f4eedb647ac60c735",
          "sha256": "91ed804482291e07987a7e9c6b1707f53c35b4bcc35e0ea29c13a9fe1e12d79b",
          "sha1": "8fd9a7973ce442765420272892b1719e3a7fef6f",
          "md5": "760bc9eb1cacc8a718ede3e45e366559"
        }
      ]
    }
  ]
}
