{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.22.aar",
          "url": "logging-0.0.22.aar",
          "size": 74087,
          "sha512": "5b95d6f4c6f7800118fa01cd155f48b1ba932732fb4815d63bab01d6b04c7987a02b125504ee84955cf89b9b2f79a10734d95dc19eaaaf46a190a57b5603adda",
          "sha256": "b1e66381783eb07eec1340667f74c714e682b892a1309947954fabd8424ced93",
          "sha1": "99cd21b2f8227e8442c894d819357e4014aae965",
          "md5": "61fe1d2468c7a657b2b8a74fef40437d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.22.aar",
          "url": "logging-0.0.22.aar",
          "size": 74087,
          "sha512": "5b95d6f4c6f7800118fa01cd155f48b1ba932732fb4815d63bab01d6b04c7987a02b125504ee84955cf89b9b2f79a10734d95dc19eaaaf46a190a57b5603adda",
          "sha256": "b1e66381783eb07eec1340667f74c714e682b892a1309947954fabd8424ced93",
          "sha1": "99cd21b2f8227e8442c894d819357e4014aae965",
          "md5": "61fe1d2468c7a657b2b8a74fef40437d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logging-0.0.22-sources.jar",
          "url": "logging-0.0.22-sources.jar",
          "size": 35768,
          "sha512": "112abc9bf583658c0f21b8bcb4d02169b82481418aa1adc9e3d758f2800e2fbdc5fb8ac7d09f665b8654e030f26a4806c991671a0e1a896d10cd044d7f483ba7",
          "sha256": "4f9cb920a5e895a95e3f9d5a920aac4e4270fa9dc948f38870876138612e683d",
          "sha1": "8b3da54056f5a04733723e5f46d056ca32d01d50",
          "md5": "00909fd743193436bf2379e54d51d763"
        }
      ]
    }
  ]
}
