{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.21.aar",
          "url": "remote-0.0.21.aar",
          "size": 12252,
          "sha512": "2b760a8e88a107d52f54be56df2a9b1a9a0bf31193def8780f5a6477d14c5153296ee32fbe17e2a308259bccb6a0a6cd8b6fea4b21fada03055ce863ada3e1a8",
          "sha256": "a5944f02747047d41ccc3f4ede2b3a2b2d4873fdb4b39bf4e4f7d9eb090bc07e",
          "sha1": "8d5d044462d83eaa04ce8be41236a5b73891d1e4",
          "md5": "ee2caf7f75b2f8349da42b2ada683e5b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.0.21.aar",
          "url": "remote-0.0.21.aar",
          "size": 12252,
          "sha512": "2b760a8e88a107d52f54be56df2a9b1a9a0bf31193def8780f5a6477d14c5153296ee32fbe17e2a308259bccb6a0a6cd8b6fea4b21fada03055ce863ada3e1a8",
          "sha256": "a5944f02747047d41ccc3f4ede2b3a2b2d4873fdb4b39bf4e4f7d9eb090bc07e",
          "sha1": "8d5d044462d83eaa04ce8be41236a5b73891d1e4",
          "md5": "ee2caf7f75b2f8349da42b2ada683e5b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-0.0.21-sources.jar",
          "url": "remote-0.0.21-sources.jar",
          "size": 10439,
          "sha512": "9e74199ce4ebf47a48e2528d0e4009e75e4147c9f2e70aa6de91f3d9aa8015c617fea1f2e5dc662e4cd9ccd77a806d5f612b35c123ed67de30827ca2cb001f52",
          "sha256": "1b4f7e046d092b253dc226d077f1e429aa56e203b6b1a4648dd4d58e56c00c17",
          "sha1": "fe63132d088b80b6b7b62644784a0bc232271b9f",
          "md5": "48dbfe462e039656a14810b8a7f582d8"
        }
      ]
    }
  ]
}
