{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "di",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.0.3.aar",
          "url": "di-1.0.3.aar",
          "size": 1753,
          "sha512": "3e7478da18251bd01d7d555437bab99c715b5b98b1a806c9db8d75f938552c0b7f7ecf6be7ad813e48128b578cbddb212e41987125dc1f64907c13c20889c6dc",
          "sha256": "2dcbb6507f1a7199cf9603411339a80a280bd4ed24772809adf8c83396dc184e",
          "sha1": "503376efa19b277fcb176d0c18b32db5bcc71baa",
          "md5": "37f4ee31c27ca0bce74837eca4fce421"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.0.3.aar",
          "url": "di-1.0.3.aar",
          "size": 1753,
          "sha512": "3e7478da18251bd01d7d555437bab99c715b5b98b1a806c9db8d75f938552c0b7f7ecf6be7ad813e48128b578cbddb212e41987125dc1f64907c13c20889c6dc",
          "sha256": "2dcbb6507f1a7199cf9603411339a80a280bd4ed24772809adf8c83396dc184e",
          "sha1": "503376efa19b277fcb176d0c18b32db5bcc71baa",
          "md5": "37f4ee31c27ca0bce74837eca4fce421"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "di-1.0.3-sources.jar",
          "url": "di-1.0.3-sources.jar",
          "size": 895,
          "sha512": "8d8c05f0e6126fbf0d33f9976d218f69d045572fe2dafff3f9401a581c5aba180a262a51a3969cd1cc115a5dbc1f80801d44676049b0cfc9d94569af97e9edc4",
          "sha256": "d4e264a49440c4bbfca930ca494829465ebdefcc473665f3ce816e19bf997627",
          "sha1": "2193cf3d344066b22ebfc38855dbc897cfd7dd91",
          "md5": "b83194de52f13ccf21f9febbd199788c"
        }
      ]
    }
  ]
}
