{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "di",
    "version": "1.1.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.1.0-snapshot.aar",
          "url": "di-1.1.0-snapshot.aar",
          "size": 1745,
          "sha512": "1e8acdaeb82ccd7b83991a8bac439f2daf0390cc4fc35770ab0a47682b6b86e27ccdf907575f55ec4a675e2be666a79eb6083525ec32468ebd57292b741d085a",
          "sha256": "a290361ce7011eb5ab452486a392655e9d12668ecaba39dda32a2ff4bbfecff5",
          "sha1": "c14308f8085c237098fe281a8396affc09b6a607",
          "md5": "9fa3c5c6333feda6afdf9288edc657de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.1.0-snapshot.aar",
          "url": "di-1.1.0-snapshot.aar",
          "size": 1745,
          "sha512": "1e8acdaeb82ccd7b83991a8bac439f2daf0390cc4fc35770ab0a47682b6b86e27ccdf907575f55ec4a675e2be666a79eb6083525ec32468ebd57292b741d085a",
          "sha256": "a290361ce7011eb5ab452486a392655e9d12668ecaba39dda32a2ff4bbfecff5",
          "sha1": "c14308f8085c237098fe281a8396affc09b6a607",
          "md5": "9fa3c5c6333feda6afdf9288edc657de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "di-1.1.0-snapshot-sources.jar",
          "url": "di-1.1.0-snapshot-sources.jar",
          "size": 895,
          "sha512": "8d8c05f0e6126fbf0d33f9976d218f69d045572fe2dafff3f9401a581c5aba180a262a51a3969cd1cc115a5dbc1f80801d44676049b0cfc9d94569af97e9edc4",
          "sha256": "d4e264a49440c4bbfca930ca494829465ebdefcc473665f3ce816e19bf997627",
          "sha1": "2193cf3d344066b22ebfc38855dbc897cfd7dd91",
          "md5": "b83194de52f13ccf21f9febbd199788c"
        }
      ]
    }
  ]
}
