{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "1.0.4-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.4-snapshot-1.aar",
          "url": "logging-1.0.4-snapshot-1.aar",
          "size": 57127,
          "sha512": "28fee83f14e102d9a6d7adab0b594c56eab74b26dcfe8fb19ee78c4e4568c66d0898e63ceeec24768c95e5f1a79cc68ad232b57ab63fb22fc19a0dd582c73c41",
          "sha256": "9b84caeffe861b75d27e134c3d0adb55bc82adaf1a096f2f04aaf7c34c8d8c85",
          "sha1": "1f25c99e94d735bb34d740b44210ab687b89f217",
          "md5": "24587ae8b6fb5d325d41a05f073d016c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.4-snapshot-1"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.4-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.4-snapshot-1.aar",
          "url": "logging-1.0.4-snapshot-1.aar",
          "size": 57127,
          "sha512": "28fee83f14e102d9a6d7adab0b594c56eab74b26dcfe8fb19ee78c4e4568c66d0898e63ceeec24768c95e5f1a79cc68ad232b57ab63fb22fc19a0dd582c73c41",
          "sha256": "9b84caeffe861b75d27e134c3d0adb55bc82adaf1a096f2f04aaf7c34c8d8c85",
          "sha1": "1f25c99e94d735bb34d740b44210ab687b89f217",
          "md5": "24587ae8b6fb5d325d41a05f073d016c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.0.4-snapshot-1-sources.jar",
          "url": "logging-1.0.4-snapshot-1-sources.jar",
          "size": 24106,
          "sha512": "35a5bdc1871d34733f76f0d2cdc86c998ae13a892cfaeed5ccc3cb1cab8ed0f4f2ce7341384a813891aeab630ba1c44e800f617dad299584f51a41a76cc022fd",
          "sha256": "e7b89e4ed7ebd774edd584129fe0add8cca71acc27a330629f49cd179d61b1b7",
          "sha1": "af07edc7a0324c3cf441bff37af2b824e25bab5c",
          "md5": "8f3b06bf63607b58c22c50a18ff1236a"
        }
      ]
    }
  ]
}
