{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.25.aar",
          "url": "core-0.0.25.aar",
          "size": 11520,
          "sha512": "6d8316a53e1fb40f8d955b39af2e55897ab2510307adc30be144151de50cb510993f715cfe1981952f33cd46960e5b5013ecd1241db71c88f26173b448ef8e91",
          "sha256": "8465ccc0f375195717981a4cc56387ba546d705c748b7823fbe95837285ecf33",
          "sha1": "28b5bfcb174040208921024ecdc109bf70824adc",
          "md5": "6a8ce663682141292cdd38a74e6a5a0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.25.aar",
          "url": "core-0.0.25.aar",
          "size": 11520,
          "sha512": "6d8316a53e1fb40f8d955b39af2e55897ab2510307adc30be144151de50cb510993f715cfe1981952f33cd46960e5b5013ecd1241db71c88f26173b448ef8e91",
          "sha256": "8465ccc0f375195717981a4cc56387ba546d705c748b7823fbe95837285ecf33",
          "sha1": "28b5bfcb174040208921024ecdc109bf70824adc",
          "md5": "6a8ce663682141292cdd38a74e6a5a0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.0.25-sources.jar",
          "url": "core-0.0.25-sources.jar",
          "size": 4248,
          "sha512": "5c59e82f1585b6b2d6e3ad461c02899db6a0c52a3589a64e2e15a89f84bf7ce25c9efe02ac4942285b22cde6c56e778fd57f4945f1842d36f4dfdf67c8453784",
          "sha256": "6a1a9b005bb927bfba002048c67f5b38f64d8094db56e756f24d121c8fc6d3b8",
          "sha1": "886fa5385828658bf0ff7ddec1a2845851f99ae7",
          "md5": "b165f95223720d0c25c7c04244dfb113"
        }
      ]
    }
  ]
}
