{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "1.0.2-rn",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.2-rn.aar",
          "url": "remote-1.0.2-rn.aar",
          "size": 12600,
          "sha512": "0a6308370f32022437502764e91a637ef06763a0c5a7e0a7db74d60c19ae82040a85efdc30771e25c299e6eae65b54b97f7beea80e4ae3fc2f380c0c0cb46f0b",
          "sha256": "05fffcd0fdc4ad0c88baabacae0ac53fcc1ff8b62faef00ec86d788b8b7d3e7d",
          "sha1": "f1d98b536512bd0f28942ca56005ce272019b640",
          "md5": "72d33369b4907215073753d64b1b8339"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "1.0.2-rn"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "1.0.2-rn"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.2-rn.aar",
          "url": "remote-1.0.2-rn.aar",
          "size": 12600,
          "sha512": "0a6308370f32022437502764e91a637ef06763a0c5a7e0a7db74d60c19ae82040a85efdc30771e25c299e6eae65b54b97f7beea80e4ae3fc2f380c0c0cb46f0b",
          "sha256": "05fffcd0fdc4ad0c88baabacae0ac53fcc1ff8b62faef00ec86d788b8b7d3e7d",
          "sha1": "f1d98b536512bd0f28942ca56005ce272019b640",
          "md5": "72d33369b4907215073753d64b1b8339"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-1.0.2-rn-sources.jar",
          "url": "remote-1.0.2-rn-sources.jar",
          "size": 6890,
          "sha512": "47f557c0c7db0e14bb51e31da4dcc091a3f3db92b786a7966760d4334e4ae02cff0bf87aedc02bf9ad869383b5458fe88d29bd1ade04117d1d63f3c56a82b19b",
          "sha256": "14f93f41b12831671f3bd04401d98e660838cbc2dbd332a0059b40082219d10e",
          "sha1": "7cc8c6fa3e8bf9a23310b99666e995b73140757e",
          "md5": "c2cefeba9b1ddff425171468f765eb46"
        }
      ]
    }
  ]
}
