{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "facetecsdk",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.135"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-2.0.4.aar",
          "url": "facetecsdk-2.0.4.aar",
          "size": 607511,
          "sha512": "5aebcaa7854e1414edb282cdc19a31e3c1f09d9d536b9f7dd5dee3a62e8a4c72554edd2cfac59d46a901f14c8059ce9fca8e6b24018fc9278077539e6b34c27d",
          "sha256": "4aec34d9834dd34f0831b2da36925a75155233bb95100fc2d8620ddd1b973bb4",
          "sha1": "754d3720573e466a3ae476469bb3dd5915af0ee6",
          "md5": "d8ce439f2921f12c5bd02cadd663ad6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "di",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.facetec",
          "module": "sdk",
          "version": {
            "requires": "9.7.135"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "facetecsdk-2.0.4.aar",
          "url": "facetecsdk-2.0.4.aar",
          "size": 607511,
          "sha512": "5aebcaa7854e1414edb282cdc19a31e3c1f09d9d536b9f7dd5dee3a62e8a4c72554edd2cfac59d46a901f14c8059ce9fca8e6b24018fc9278077539e6b34c27d",
          "sha256": "4aec34d9834dd34f0831b2da36925a75155233bb95100fc2d8620ddd1b973bb4",
          "sha1": "754d3720573e466a3ae476469bb3dd5915af0ee6",
          "md5": "d8ce439f2921f12c5bd02cadd663ad6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "facetecsdk-2.0.4-sources.jar",
          "url": "facetecsdk-2.0.4-sources.jar",
          "size": 112707,
          "sha512": "7243936578ca672ab476932a0e78037ef8bcdd63ecceaa7c6772bcaa6e7918c94d770fe3059117af2ad01f8645ce45075e59c4381a84bdeb87c07ce006f1eada",
          "sha256": "673dce815a88e221b8732205c0d9f9d8d8415c2f1e32056d8145040839ca69de",
          "sha1": "9a7d356d1b98b406059f23544dc0e59fadc580bc",
          "md5": "ec6b94e814b144545a384f7f0c0e75a0"
        }
      ]
    }
  ]
}
