{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "0.0.20-layout-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.20-layout-fix.aar",
          "url": "domain-0.0.20-layout-fix.aar",
          "size": 140629,
          "sha512": "0cf4ca8ea00b5fb8f12e2065193fc771c2f02f3c23ca538e365b721b26d6ac2072f1ffe1a1c64df67c40e36b1a7c5d9b3a0f7a5b8d72541220170c069aa5eb4c",
          "sha256": "3d70f1f00db5d513e135a5e5fd1a0278c21c57a9f0ee32096e1e567e0da2517e",
          "sha1": "f3cc7257ab8f48bd38761466a747781e5f1ce9e2",
          "md5": "5334df3e8be0a4a4af120c9ea5c78bc1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.20-layout-fix.aar",
          "url": "domain-0.0.20-layout-fix.aar",
          "size": 140629,
          "sha512": "0cf4ca8ea00b5fb8f12e2065193fc771c2f02f3c23ca538e365b721b26d6ac2072f1ffe1a1c64df67c40e36b1a7c5d9b3a0f7a5b8d72541220170c069aa5eb4c",
          "sha256": "3d70f1f00db5d513e135a5e5fd1a0278c21c57a9f0ee32096e1e567e0da2517e",
          "sha1": "f3cc7257ab8f48bd38761466a747781e5f1ce9e2",
          "md5": "5334df3e8be0a4a4af120c9ea5c78bc1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "domain-0.0.20-layout-fix-sources.jar",
          "url": "domain-0.0.20-layout-fix-sources.jar",
          "size": 59413,
          "sha512": "a261e312ac2106b64778d307c3cc7ad590d9580b4c47bbecac3b2b1ab9dbe16bbf93ed74edeee4fdca155c7da684061d8f34c195777655d540beb4cf5149b9d3",
          "sha256": "5c9fb42b4bb493055a1cdf916852e1d49eb1ca2e2c91da142cf316c2e7820467",
          "sha1": "29838b80b8e5a4662f3d3606f7d623523230e712",
          "md5": "e0354e38d8a00ef2c18064284fb845fb"
        }
      ]
    }
  ]
}
