{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.2.aar",
          "url": "core-1.0.2.aar",
          "size": 11559,
          "sha512": "3e5a509606d21dd616cc82b1955e0cd041d8130552b725684deb6f3cb3d81dc029cc7bba61f378e971576a4c6511566dc5b3f32ac8686c48ed42133ac778ec88",
          "sha256": "636e99fd4006744af0a31a9b74747890999b75a2244defa8526e6b3c564f0682",
          "sha1": "f92b2d8a3a960c188cce24e5ab1dcee6cfefe762",
          "md5": "4d6e0284b9f91c446a6e3be1f7ba00e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.2.aar",
          "url": "core-1.0.2.aar",
          "size": 11559,
          "sha512": "3e5a509606d21dd616cc82b1955e0cd041d8130552b725684deb6f3cb3d81dc029cc7bba61f378e971576a4c6511566dc5b3f32ac8686c48ed42133ac778ec88",
          "sha256": "636e99fd4006744af0a31a9b74747890999b75a2244defa8526e6b3c564f0682",
          "sha1": "f92b2d8a3a960c188cce24e5ab1dcee6cfefe762",
          "md5": "4d6e0284b9f91c446a6e3be1f7ba00e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.2-sources.jar",
          "url": "core-1.0.2-sources.jar",
          "size": 4283,
          "sha512": "252c0347cc16d1cc48aa3ad05d140af3cff6e33fe93b05e763dceffb02007bb7165fa1cf5aabb46948b13811f87a26180587e840bdce762e5cdd646d51b066bc",
          "sha256": "b0f4244abf2d7a9354161bef3d9ef347847b5330347712d4b94942e1d7f836c6",
          "sha1": "a788ca659e9399e49a8c8779c4b63f4a9b72d3bf",
          "md5": "317af4ef6aa26db21f3e4141b29e2e7f"
        }
      ]
    }
  ]
}
