{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "di",
    "version": "1.0.2-rn",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.0.2-rn.aar",
          "url": "di-1.0.2-rn.aar",
          "size": 1748,
          "sha512": "227d604243f0dda7a534af2a9af41a9cf5c6a70e15bc90bfce18e2bb4d0080e22e9769f7abe7e21346f789f839a87c96bb70d92135356f1aee1508fe92f7fc66",
          "sha256": "442f45b5bdc2b27fd2b1f2c1a9f52a8c746d9d77aa35f7ff52054ae418185f4e",
          "sha1": "ee6872ff0a9b03ecd7a4c5dce739fa8253fb98f6",
          "md5": "4e406184521d3158e658c34194814775"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "di-1.0.2-rn.aar",
          "url": "di-1.0.2-rn.aar",
          "size": 1748,
          "sha512": "227d604243f0dda7a534af2a9af41a9cf5c6a70e15bc90bfce18e2bb4d0080e22e9769f7abe7e21346f789f839a87c96bb70d92135356f1aee1508fe92f7fc66",
          "sha256": "442f45b5bdc2b27fd2b1f2c1a9f52a8c746d9d77aa35f7ff52054ae418185f4e",
          "sha1": "ee6872ff0a9b03ecd7a4c5dce739fa8253fb98f6",
          "md5": "4e406184521d3158e658c34194814775"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "di-1.0.2-rn-sources.jar",
          "url": "di-1.0.2-rn-sources.jar",
          "size": 895,
          "sha512": "8d8c05f0e6126fbf0d33f9976d218f69d045572fe2dafff3f9401a581c5aba180a262a51a3969cd1cc115a5dbc1f80801d44676049b0cfc9d94569af97e9edc4",
          "sha256": "d4e264a49440c4bbfca930ca494829465ebdefcc473665f3ce816e19bf997627",
          "sha1": "2193cf3d344066b22ebfc38855dbc897cfd7dd91",
          "md5": "b83194de52f13ccf21f9febbd199788c"
        }
      ]
    }
  ]
}
