{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "iproovsdk",
    "version": "1.0.4-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "iproovsdk-1.0.4-snapshot.aar",
          "url": "iproovsdk-1.0.4-snapshot.aar",
          "size": 272736,
          "sha512": "86ed3c6b89d4351cd3255a2dec885d92597b45ccb933e04001c29287c99df95e2fba578273595b6508b8e2c409077743c604301fe4536256fb4fa1b8173f852b",
          "sha256": "fbec12dc4737d8431f2957b9fa5bd5bb7b9a42295175249041e5ac65c378457f",
          "sha1": "7ee0182474678f9611209b99a67731a3784ebf18",
          "md5": "89b7c64515f50c1975bee1bc8f92a166"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "1.0.4-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.4-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "1.0.4-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "1.0.4-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "1.0.4-snapshot"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.4-snapshot"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "iproovsdk-1.0.4-snapshot.aar",
          "url": "iproovsdk-1.0.4-snapshot.aar",
          "size": 272736,
          "sha512": "86ed3c6b89d4351cd3255a2dec885d92597b45ccb933e04001c29287c99df95e2fba578273595b6508b8e2c409077743c604301fe4536256fb4fa1b8173f852b",
          "sha256": "fbec12dc4737d8431f2957b9fa5bd5bb7b9a42295175249041e5ac65c378457f",
          "sha1": "7ee0182474678f9611209b99a67731a3784ebf18",
          "md5": "89b7c64515f50c1975bee1bc8f92a166"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iproovsdk-1.0.4-snapshot-sources.jar",
          "url": "iproovsdk-1.0.4-snapshot-sources.jar",
          "size": 32811,
          "sha512": "7e617171c44764c6558885a103d6e1083871d6957f42f0b53e92acd4958dce131301d64c9086fa1886c428a8d5c68fd055f8faa5cee7adaeeae6500c444173d3",
          "sha256": "cd162afa7433856ac2d08fd200c424b0bf06dab34137859edae567d4e6657839",
          "sha1": "b5052e2e6ce4abf518972c2637d84e49fc5e6247",
          "md5": "556c0e0d079fedafa14711cdd10bc9b6"
        }
      ]
    }
  ]
}
