{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "core",
    "version": "1.0.2-rn",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.2-rn.aar",
          "url": "core-1.0.2-rn.aar",
          "size": 11535,
          "sha512": "948a112c13785868ad86ba775ccef5b47c1e295ea10aaae1386c8d76b822d4b8c2c908151db80e39ab5afc4ae21b52d0ab9ae92a4f67c84fbf3448ae97f25170",
          "sha256": "4b5a2ad3905caf3f1fe6a02d0430209c0459561da8c87701181cb2bb24d8da63",
          "sha1": "a9def5e262c023cb9cb98f7e7d2e945695dd3c66",
          "md5": "c6db5fade0e7656687be8f002e8bf5cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.2-rn.aar",
          "url": "core-1.0.2-rn.aar",
          "size": 11535,
          "sha512": "948a112c13785868ad86ba775ccef5b47c1e295ea10aaae1386c8d76b822d4b8c2c908151db80e39ab5afc4ae21b52d0ab9ae92a4f67c84fbf3448ae97f25170",
          "sha256": "4b5a2ad3905caf3f1fe6a02d0430209c0459561da8c87701181cb2bb24d8da63",
          "sha1": "a9def5e262c023cb9cb98f7e7d2e945695dd3c66",
          "md5": "c6db5fade0e7656687be8f002e8bf5cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.0.2-rn-sources.jar",
          "url": "core-1.0.2-rn-sources.jar",
          "size": 4283,
          "sha512": "252c0347cc16d1cc48aa3ad05d140af3cff6e33fe93b05e763dceffb02007bb7165fa1cf5aabb46948b13811f87a26180587e840bdce762e5cdd646d51b066bc",
          "sha256": "b0f4244abf2d7a9354161bef3d9ef347847b5330347712d4b94942e1d7f836c6",
          "sha1": "a788ca659e9399e49a8c8779c4b63f4a9b72d3bf",
          "md5": "317af4ef6aa26db21f3e4141b29e2e7f"
        }
      ]
    }
  ]
}
