{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "utils",
    "version": "1.0.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.0-snapshot-3.aar",
          "url": "utils-1.0.0-snapshot-3.aar",
          "size": 127787,
          "sha512": "3ee6c0a2de75feb19a03ddedb8e11c84610266f3def90d077c3900359b2eaea37c4060796776b7963cfd7057763d251232e0e2718c4a755772902256b8d82d3f",
          "sha256": "7891fa4124d589aa56f769809a88e43146f01ef03f2c2494ed2751f06c993069",
          "sha1": "b655ef8b587fcfe4cac90182289edb189cb4f755",
          "md5": "76ce664bdfd84e44be1c461048fb74b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.81"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "1.0.0-snapshot-3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.0.0-snapshot-3.aar",
          "url": "utils-1.0.0-snapshot-3.aar",
          "size": 127787,
          "sha512": "3ee6c0a2de75feb19a03ddedb8e11c84610266f3def90d077c3900359b2eaea37c4060796776b7963cfd7057763d251232e0e2718c4a755772902256b8d82d3f",
          "sha256": "7891fa4124d589aa56f769809a88e43146f01ef03f2c2494ed2751f06c993069",
          "sha1": "b655ef8b587fcfe4cac90182289edb189cb4f755",
          "md5": "76ce664bdfd84e44be1c461048fb74b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.0.0-snapshot-3-sources.jar",
          "url": "utils-1.0.0-snapshot-3-sources.jar",
          "size": 34130,
          "sha512": "cc29612d4dc599a801a502d251feaebd865954293b191c5827ae376a84558f64fa69bb9eab949c21ae099b9bcb7f887feb7a149f8048cd6a9bd98e6bb468ad3c",
          "sha256": "273b9edd652a7dc8d3499a5e93d0750d0ae09df917197b2102b8169c5de22ca6",
          "sha1": "dc80a6ec36db79ec8495c7bce723d5c221772d92",
          "md5": "b472e1428b30480f433cbae2f97dfe31"
        }
      ]
    }
  ]
}
