{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "1.0.3-snapshot-iproov",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.0.3-snapshot-iproov.aar",
          "url": "data-1.0.3-snapshot-iproov.aar",
          "size": 186515,
          "sha512": "577f3d92e9ce58cc6b0ffb92b979dd411303e8ba813773bf22fceac55da33a781e600756f2d713dc712df60bb554d5ff18f486db3b97d1c9dec8e12eafb1a73f",
          "sha256": "907929f898435cda7728d491222c4e0b80b29db0c072c5a64fad9122c7072a5d",
          "sha1": "b5ee386e2146f0868b9ad8a0a90c66447be8a770",
          "md5": "625e74612d9bb8850a36e06dbd06f8df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "1.0.3-snapshot-iproov"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "1.0.3-snapshot-iproov"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "1.0.3-snapshot-iproov"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.3-snapshot-iproov"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.0.3-snapshot-iproov.aar",
          "url": "data-1.0.3-snapshot-iproov.aar",
          "size": 186515,
          "sha512": "577f3d92e9ce58cc6b0ffb92b979dd411303e8ba813773bf22fceac55da33a781e600756f2d713dc712df60bb554d5ff18f486db3b97d1c9dec8e12eafb1a73f",
          "sha256": "907929f898435cda7728d491222c4e0b80b29db0c072c5a64fad9122c7072a5d",
          "sha1": "b5ee386e2146f0868b9ad8a0a90c66447be8a770",
          "md5": "625e74612d9bb8850a36e06dbd06f8df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.0.3-snapshot-iproov-sources.jar",
          "url": "data-1.0.3-snapshot-iproov-sources.jar",
          "size": 19375,
          "sha512": "b5ca83a1ce44fca7e40a2f64ea78ab37d17370528db72ba1326b644c89402714fadfbc5495d14a07cc6c19f5537a4a32d8e26543e478e2ba28a62e2f573ca932",
          "sha256": "8e1c314caee54c092bc946a96cddff295469b9ae51ef1b323bc0f144d1a2ed22",
          "sha1": "33705da5a65ad42aa2db3810e32d450ea4c08e19",
          "md5": "20ec7e99a3c1fe12921f2d394386128d"
        }
      ]
    }
  ]
}
