{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oitisdk",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "facetecsdk",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.24.aar",
          "url": "oitisdk-0.0.24.aar",
          "size": 58091,
          "sha512": "7f39408274c7dd303e3a9ce89b3eb47b2d1a36ae03cbab9f9277cf20e00b8759b04529a89dd9d05cc0aa05cc92937b8249ce44891d5dbe40bd67a5f0b11c287f",
          "sha256": "d4aee88eaaa9f12c69a13fcf330ddfa8906a1f16cc5a878b8fadf33c7fbcaad8",
          "sha1": "419d3cf7850e71f45555589a3e8114d83f553644",
          "md5": "c9ef716e01f48ca3d058e6cede6903c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.08.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "di",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "logging",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "data",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "iproovsdk",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "facetecsdk",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oitisdk-0.0.24.aar",
          "url": "oitisdk-0.0.24.aar",
          "size": 58091,
          "sha512": "7f39408274c7dd303e3a9ce89b3eb47b2d1a36ae03cbab9f9277cf20e00b8759b04529a89dd9d05cc0aa05cc92937b8249ce44891d5dbe40bd67a5f0b11c287f",
          "sha256": "d4aee88eaaa9f12c69a13fcf330ddfa8906a1f16cc5a878b8fadf33c7fbcaad8",
          "sha1": "419d3cf7850e71f45555589a3e8114d83f553644",
          "md5": "c9ef716e01f48ca3d058e6cede6903c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oitisdk-0.0.24-sources.jar",
          "url": "oitisdk-0.0.24-sources.jar",
          "size": 24516,
          "sha512": "35a3c45a89066a5b4403ab815eb17ed10887c6b63b411bb9f6f74f4b3bfa28bac3268d2bc3146c22ecfc58c2739f1babe66b8812a003796c4d1e71430e9b6aef",
          "sha256": "737c93c9e0d741df7d99556e9305cd63517b148f4b28639ab2bdd78ff374b945",
          "sha1": "a7fe4afb317823a88472dadaf4c0576c74a2076e",
          "md5": "174b294af6dd59718abe4894b97aea14"
        }
      ]
    }
  ]
}
