{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.1.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.0-snapshot-2.aar",
          "url": "domain-1.1.0-snapshot-2.aar",
          "size": 158747,
          "sha512": "dbce12a7ce6347c0fd6955624bbe9356d6bfbce666257c8789437da274f4141af0f5ec24072a60c42980af48054b113482ad4d8fe332f99a42ee4aa0b7b1cad1",
          "sha256": "1192d0c2be58c4fa37c036aedbee4c033a96318f2354d031e655a4b043cd1496",
          "sha1": "7182f45fc40e209415f5aebce57145109f54b613",
          "md5": "cd24a78684b14fa84a08a7822f17d85b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.1.0-snapshot-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.1.0-snapshot-2.aar",
          "url": "domain-1.1.0-snapshot-2.aar",
          "size": 158747,
          "sha512": "dbce12a7ce6347c0fd6955624bbe9356d6bfbce666257c8789437da274f4141af0f5ec24072a60c42980af48054b113482ad4d8fe332f99a42ee4aa0b7b1cad1",
          "sha256": "1192d0c2be58c4fa37c036aedbee4c033a96318f2354d031e655a4b043cd1496",
          "sha1": "7182f45fc40e209415f5aebce57145109f54b613",
          "md5": "cd24a78684b14fa84a08a7822f17d85b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.1.0-snapshot-2-sources.jar",
          "url": "domain-1.1.0-snapshot-2-sources.jar",
          "size": 39227,
          "sha512": "64430c9bef4a1a24300b52254c9b8bf0919e03ebd344b3e1ae6e67fbb79dd0c4aa4f2134704a2d3b727cf7f45980f6bbc939296514e34a3f1c2195c28f74927e",
          "sha256": "efc517e4dc9371276831abe83400d6ffb07239eccf1d6a280438758f13c8b526",
          "sha1": "41cf1eabd526d2e268c43de8f3064b2e2ef162ef",
          "md5": "cfde8a4607273a8852249e5df02f9f35"
        }
      ]
    }
  ]
}
