{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "1.0.4-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.4-snapshot.aar",
          "url": "designsystem-1.0.4-snapshot.aar",
          "size": 1873352,
          "sha512": "085ae46b1b78a75ef5da572840d1ef6303f0fb427be0b6182ac6cab61cc5aeeff2f45d843f1fa432d5bec1c945e5b22772e4def6911c63fb3ea311029fb78b82",
          "sha256": "23481d4d00e9e4e0fd7ddd05491e18228770eead055d36f500235948b586a210",
          "sha1": "824195e1d5b4c8a56be98710a8d292feb9b956d7",
          "md5": "3cc720efad2c4ce893d297deb7b0d14e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.4-snapshot.aar",
          "url": "designsystem-1.0.4-snapshot.aar",
          "size": 1873352,
          "sha512": "085ae46b1b78a75ef5da572840d1ef6303f0fb427be0b6182ac6cab61cc5aeeff2f45d843f1fa432d5bec1c945e5b22772e4def6911c63fb3ea311029fb78b82",
          "sha256": "23481d4d00e9e4e0fd7ddd05491e18228770eead055d36f500235948b586a210",
          "sha1": "824195e1d5b4c8a56be98710a8d292feb9b956d7",
          "md5": "3cc720efad2c4ce893d297deb7b0d14e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.4-snapshot-sources.jar",
          "url": "designsystem-1.0.4-snapshot-sources.jar",
          "size": 28915,
          "sha512": "8f8ef6cd68565992e102a78b4f0840e26c35f9eb14b113b3dbc643171e92506f260b13da262abce0cf6834ca98756bce4bcf221de7793764a9539642f6b2692d",
          "sha256": "fbd38cd5bc23707801c852df147dde744f11b09623a9d427b4fd762ec7c2fc1a",
          "sha1": "f9d6bd9fce190e95eaf3bb11c77dd33f759dd218",
          "md5": "0db31fa28abede622db329ecf3d8b383"
        }
      ]
    }
  ]
}
