{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "1.0.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-2.aar",
          "url": "designsystem-1.0.0-snapshot-2.aar",
          "size": 1903875,
          "sha512": "063075b61100fcab237d46729d3e7cbe65a5b3bfa104f8570a24333ce2fdc8c75fbe69c2b06262311b741f7f76c53c4cd6d11b3b999e3d9de08f4c20d0835fc2",
          "sha256": "9d1618197924653c5e03f4f7c9db432f9a74438905d238da61ad22c3d49e8275",
          "sha1": "e3650c169009990a7661f6880e82a3d03edd10f6",
          "md5": "6db3cade12da730c755e0bba301201a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-2.aar",
          "url": "designsystem-1.0.0-snapshot-2.aar",
          "size": 1903875,
          "sha512": "063075b61100fcab237d46729d3e7cbe65a5b3bfa104f8570a24333ce2fdc8c75fbe69c2b06262311b741f7f76c53c4cd6d11b3b999e3d9de08f4c20d0835fc2",
          "sha256": "9d1618197924653c5e03f4f7c9db432f9a74438905d238da61ad22c3d49e8275",
          "sha1": "e3650c169009990a7661f6880e82a3d03edd10f6",
          "md5": "6db3cade12da730c755e0bba301201a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-2-sources.jar",
          "url": "designsystem-1.0.0-snapshot-2-sources.jar",
          "size": 28008,
          "sha512": "ee638a8c74acdedee884a12b058ac589f9e40ec3c3c4886ef146c7a1a559de668d7e955c62195071e8c85c448825b8eac3e20a4ea5b79b03f23395a0a1acc973",
          "sha256": "6926d85efd66252a8fcb98ac85fbedfc8a5204589144ae2e4f0b2b0b330b1caf",
          "sha1": "7f3c15e9d0908fc20d59f32cbc1c16e502962b23",
          "md5": "8fd3f1664730d22db81a259ec57994cb"
        }
      ]
    }
  ]
}
