{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "logging",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.26.aar",
          "url": "logging-0.0.26.aar",
          "size": 61694,
          "sha512": "845e33d32cbfdafaa286c09b1341ccce37e076a85d3f56dcd0bd707a7ff72f31de967fa91fb42f955a608f6a04e075635f20e002c805bee17a75aa48c6a18b3d",
          "sha256": "d4a151add7fd0801f4c52b571e36c912aff0583007dc5321b6d5c3c0f2de58c5",
          "sha1": "dc845b90b0f72793675d574ca46309dda792d11c",
          "md5": "b8b58812d4160a77876f0f827561d9f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.26.aar",
          "url": "logging-0.0.26.aar",
          "size": 61694,
          "sha512": "845e33d32cbfdafaa286c09b1341ccce37e076a85d3f56dcd0bd707a7ff72f31de967fa91fb42f955a608f6a04e075635f20e002c805bee17a75aa48c6a18b3d",
          "sha256": "d4a151add7fd0801f4c52b571e36c912aff0583007dc5321b6d5c3c0f2de58c5",
          "sha1": "dc845b90b0f72793675d574ca46309dda792d11c",
          "md5": "b8b58812d4160a77876f0f827561d9f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-0.0.26-sources.jar",
          "url": "logging-0.0.26-sources.jar",
          "size": 24325,
          "sha512": "ce4ddd191062088e7e9535e4cfb987b7c2d7d60fadeb7eced1622be9508f0f46643fbc337bc317db276fc84a835192737b77d9a9cd0168315a31711cc35db07c",
          "sha256": "f434781eb7b3c9c6807538555c8d2d5d5648200b92be67b553bf57a4644838ba",
          "sha1": "e12d8d59a9c71142c76481906663cc61413bec27",
          "md5": "39979ccb1cb4faa74898bc2a7dc7227f"
        }
      ]
    }
  ]
}
