{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "0.0.20-layout-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.20-layout-fix.aar",
          "url": "data-0.0.20-layout-fix.aar",
          "size": 194282,
          "sha512": "6a63cb2547567407cce1acbba38fa8ef47cd4796dd40662b96cb0d0e21e3bdc3e168bf64b1deea6d93c813ca5c090bff71c60447383c756f702b75c26ab3d3e3",
          "sha256": "c2d2840c832a530378cac2df69280e063db3c3b36c9311592f7c548ce1b488cd",
          "sha1": "1c04b655978b4077a36eb8b491924a85804da903",
          "md5": "87dd29fb4a506fa4d6182a345b1ffedd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.20-layout-fix"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.20-layout-fix.aar",
          "url": "data-0.0.20-layout-fix.aar",
          "size": 194282,
          "sha512": "6a63cb2547567407cce1acbba38fa8ef47cd4796dd40662b96cb0d0e21e3bdc3e168bf64b1deea6d93c813ca5c090bff71c60447383c756f702b75c26ab3d3e3",
          "sha256": "c2d2840c832a530378cac2df69280e063db3c3b36c9311592f7c548ce1b488cd",
          "sha1": "1c04b655978b4077a36eb8b491924a85804da903",
          "md5": "87dd29fb4a506fa4d6182a345b1ffedd"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-0.0.20-layout-fix-sources.jar",
          "url": "data-0.0.20-layout-fix-sources.jar",
          "size": 27359,
          "sha512": "ea2bd21850543eb73ce3692add6b60064ef8580b526b900f762f4928c2b117e63c0eae7cc47f9450e4af5e79d513dcd342cc67359ab27198e47fa48bec0d7a54",
          "sha256": "68012342a2ead81837128235f33acc730f105a55fdc4b96b50c24eeca8330f38",
          "sha1": "20207eb77086b589e7f4c1157f79e70ced310e17",
          "md5": "43173ca9949b0d2c51026335bcfb5796"
        }
      ]
    }
  ]
}
