{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "remote",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.2.aar",
          "url": "remote-1.0.2.aar",
          "size": 12625,
          "sha512": "38d4c5608c70977bff9009b5f055a686ea360d367f83550039af51c461625357dee6f1699d0448947c5a4769e2ac053e2bf98066a9b00c43de57a7da2f9a192e",
          "sha256": "c0bd5c72e72c3d10242ac56109cfc6427d91154d095d7c03f7d350f656fa7db6",
          "sha1": "e5097c31f601409eddb61db10706004a246811bf",
          "md5": "73f328a92ed8fcffe764d63329099264"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.2.aar",
          "url": "remote-1.0.2.aar",
          "size": 12625,
          "sha512": "38d4c5608c70977bff9009b5f055a686ea360d367f83550039af51c461625357dee6f1699d0448947c5a4769e2ac053e2bf98066a9b00c43de57a7da2f9a192e",
          "sha256": "c0bd5c72e72c3d10242ac56109cfc6427d91154d095d7c03f7d350f656fa7db6",
          "sha1": "e5097c31f601409eddb61db10706004a246811bf",
          "md5": "73f328a92ed8fcffe764d63329099264"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-1.0.2-sources.jar",
          "url": "remote-1.0.2-sources.jar",
          "size": 6890,
          "sha512": "47f557c0c7db0e14bb51e31da4dcc091a3f3db92b786a7966760d4334e4ae02cff0bf87aedc02bf9ad869383b5458fe88d29bd1ade04117d1d63f3c56a82b19b",
          "sha256": "14f93f41b12831671f3bd04401d98e660838cbc2dbd332a0059b40082219d10e",
          "sha1": "7cc8c6fa3e8bf9a23310b99666e995b73140757e",
          "md5": "c2cefeba9b1ddff425171468f765eb46"
        }
      ]
    }
  ]
}
