{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "data",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.22.aar",
          "url": "data-0.0.22.aar",
          "size": 197209,
          "sha512": "a7ee3c5492b50edf08b678833fbcfa509be8f9886ad1b439653ad08ab7f328f2346f43b3c4711628ab1ac3e510356c4e60ade5c031650548b53828936ffd491b",
          "sha256": "41e27500fc4c89837ff1834e59ed39e11c488c051251a32764f8e900c087a3a5",
          "sha1": "49e20ab9b37263f091778712abd22cd762bcbd55",
          "md5": "10c54d7fdb3568e90368312e062a391f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "domain",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "remote",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "oiti-network",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "data-0.0.22.aar",
          "url": "data-0.0.22.aar",
          "size": 197209,
          "sha512": "a7ee3c5492b50edf08b678833fbcfa509be8f9886ad1b439653ad08ab7f328f2346f43b3c4711628ab1ac3e510356c4e60ade5c031650548b53828936ffd491b",
          "sha256": "41e27500fc4c89837ff1834e59ed39e11c488c051251a32764f8e900c087a3a5",
          "sha1": "49e20ab9b37263f091778712abd22cd762bcbd55",
          "md5": "10c54d7fdb3568e90368312e062a391f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "data-0.0.22-sources.jar",
          "url": "data-0.0.22-sources.jar",
          "size": 27519,
          "sha512": "1425be34b92ead20e795d4db57dd8d100a27602d447b58465887e37add0750adbafed2a9aad1209f754313ed9915fd4d00c83d39b9a2f19002ad0ec5246ec8c7",
          "sha256": "c4fcf3feb52caedebb8ee761686178807442d75e46a5a6cc1487712749a6e4cd",
          "sha1": "161933425ff3ca73ce5d55f1611d2d97f61552e8",
          "md5": "67de579984bc765b0418b396fcef8b78"
        }
      ]
    }
  ]
}
