{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "designsystem",
    "version": "1.0.2-rn-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.2-rn-2.aar",
          "url": "designsystem-1.0.2-rn-2.aar",
          "size": 1944032,
          "sha512": "88e186ddf41240ca3fdba26d9b2d289436baffc3436216f0caa0bb611b5d910b7e8de51ce91c45208962958e11245790efe1561af43b48c04faa4fb1b46bc8a0",
          "sha256": "04eff967ab76e199c38e4157953911e8ae5cc6674b656ad1637a61a0e5413b83",
          "sha1": "3dce8131965f20cfb43116d3f76592d817ff7e5e",
          "md5": "11c877d63b2fc7fa62add923c09916fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.2-rn-2.aar",
          "url": "designsystem-1.0.2-rn-2.aar",
          "size": 1944032,
          "sha512": "88e186ddf41240ca3fdba26d9b2d289436baffc3436216f0caa0bb611b5d910b7e8de51ce91c45208962958e11245790efe1561af43b48c04faa4fb1b46bc8a0",
          "sha256": "04eff967ab76e199c38e4157953911e8ae5cc6674b656ad1637a61a0e5413b83",
          "sha1": "3dce8131965f20cfb43116d3f76592d817ff7e5e",
          "md5": "11c877d63b2fc7fa62add923c09916fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.2-rn-2-sources.jar",
          "url": "designsystem-1.0.2-rn-2-sources.jar",
          "size": 28915,
          "sha512": "8f8ef6cd68565992e102a78b4f0840e26c35f9eb14b113b3dbc643171e92506f260b13da262abce0cf6834ca98756bce4bcf221de7793764a9539642f6b2692d",
          "sha256": "fbd38cd5bc23707801c852df147dde744f11b09623a9d427b4fd762ec7c2fc1a",
          "sha1": "f9d6bd9fce190e95eaf3bb11c77dd33f759dd218",
          "md5": "0db31fa28abede622db329ecf3d8b383"
        }
      ]
    }
  ]
}
