{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "1.0.2-rn",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.2-rn.aar",
          "url": "domain-1.0.2-rn.aar",
          "size": 154175,
          "sha512": "610a0b470bccf9c245226585538a6551b91615fd004b333750d141ae6dd8df41dddbe7702acc9252effd4817fcfa7f145ef29cec3f9a6e7f20aa2484f20e4400",
          "sha256": "4af5dc1803748f39888eb068b84b19e7919b51b892ae3bc44426395daf7697e4",
          "sha1": "54aabb74990405f854921c7185852d146e061ed3",
          "md5": "98c9a346e765362f65842d7708ed5114"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "1.0.2-rn"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "1.0.2-rn"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.2-rn.aar",
          "url": "domain-1.0.2-rn.aar",
          "size": 154175,
          "sha512": "610a0b470bccf9c245226585538a6551b91615fd004b333750d141ae6dd8df41dddbe7702acc9252effd4817fcfa7f145ef29cec3f9a6e7f20aa2484f20e4400",
          "sha256": "4af5dc1803748f39888eb068b84b19e7919b51b892ae3bc44426395daf7697e4",
          "sha1": "54aabb74990405f854921c7185852d146e061ed3",
          "md5": "98c9a346e765362f65842d7708ed5114"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.0.2-rn-sources.jar",
          "url": "domain-1.0.2-rn-sources.jar",
          "size": 33812,
          "sha512": "d60c58965b1b3d0ec579011924dfa4d829b81d07b67859bef2ae1ff1c9df18cb9fd2b654b622e9464b37f64d5aa39242de3b22b8b19cd3d7d8440742c8696688",
          "sha256": "46669f5d33fd059a90a621d0380009d56377392465c7bcc23524505c984c9b34",
          "sha1": "27053bdd1a52b37bf9407e01fdf70d69f003ea3a",
          "md5": "b8f79103953be52edf08e3061435d97c"
        }
      ]
    }
  ]
}
