{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "domain",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.25.aar",
          "url": "domain-0.0.25.aar",
          "size": 149454,
          "sha512": "38f37222fb7562e293b5a188ead5f1cf71e824b6689b5c538d4611952dbd18c2cb5bf9e4d5e07a3e2a94bd65055d31fa0dca0d8bf69680b486bc76846abab42e",
          "sha256": "ed3a9691cd1e0b456254f34626aa4f4cad715a9b2c239d467b6465dc79a96220",
          "sha1": "92b6476bc3784392a7e13781e9461644d7f53f8f",
          "md5": "f09d998577f293ffccadb916ee6b1ce4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "designsystem",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "utils",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.25.aar",
          "url": "domain-0.0.25.aar",
          "size": 149454,
          "sha512": "38f37222fb7562e293b5a188ead5f1cf71e824b6689b5c538d4611952dbd18c2cb5bf9e4d5e07a3e2a94bd65055d31fa0dca0d8bf69680b486bc76846abab42e",
          "sha256": "ed3a9691cd1e0b456254f34626aa4f4cad715a9b2c239d467b6465dc79a96220",
          "sha1": "92b6476bc3784392a7e13781e9461644d7f53f8f",
          "md5": "f09d998577f293ffccadb916ee6b1ce4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-0.0.25-sources.jar",
          "url": "domain-0.0.25-sources.jar",
          "size": 32305,
          "sha512": "8e85b8491b34ce6ee0fcdb5bebe59deb55c91dcb8b8a577bf32f2880ccbd8d2358178ee34cedc206f57e4dd7a1a6a682881c163a3276df9cfea5ea21fdfdd625",
          "sha256": "3cbe777623958ae73d4fa68e4f1ff2611c0dce5098d1680ddc70ab1369bbdd86",
          "sha1": "22b6066335c5f1eb42d2506b753c39dd4a2d89b9",
          "md5": "3442a4a750cc7302506f71e0098d1dbc"
        }
      ]
    }
  ]
}
