{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "oiti-network",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.24.aar",
          "url": "oiti-network-0.0.24.aar",
          "size": 43034,
          "sha512": "8ba7b1503742f6298ca4a8ccb91a1ae977d971a30d6006b933bfa08b7aa980c752f479c2e0b9fe1d63ea798a3a64ce4477028d4d7177f0ea7ac67ada3a2e4cb3",
          "sha256": "c21fa079feb6f98af48aa3837e4a234ef46b8beac942d8c5079e2a8b497a7af8",
          "sha1": "0d8182367c318126f43b5c9cfc9b4988b3316fa9",
          "md5": "324404ae462c9b582c83bc2d61119fb1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.57"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "br.com.oiti",
          "module": "core",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "oiti-network-0.0.24.aar",
          "url": "oiti-network-0.0.24.aar",
          "size": 43034,
          "sha512": "8ba7b1503742f6298ca4a8ccb91a1ae977d971a30d6006b933bfa08b7aa980c752f479c2e0b9fe1d63ea798a3a64ce4477028d4d7177f0ea7ac67ada3a2e4cb3",
          "sha256": "c21fa079feb6f98af48aa3837e4a234ef46b8beac942d8c5079e2a8b497a7af8",
          "sha1": "0d8182367c318126f43b5c9cfc9b4988b3316fa9",
          "md5": "324404ae462c9b582c83bc2d61119fb1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oiti-network-0.0.24-sources.jar",
          "url": "oiti-network-0.0.24-sources.jar",
          "size": 14117,
          "sha512": "2513d4affe2598e219c6a69811f35032e8782cd7347e6ce68512ce732348db851753f945a8b6eec245210bdf3a6ebbc9a3015ba5a46ff154fd98e1d310a92d2a",
          "sha256": "78ac182ea3d73efdee7820ffa6ab30c5efa9ba8e20c621b1c86001c45ae35938",
          "sha1": "521d19f1b343e80498ad3601f2c9fbe5617a9ccc",
          "md5": "3fed7a1d52660854e61f2a92c4a82730"
        }
      ]
    }
  ]
}
